package net.steamcrafted.materialiconlib;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.ColorFilter;
import android.graphics.Paint;
import android.graphics.Rect;
import android.graphics.drawable.Drawable;
import android.text.TextPaint;

public class MaterialDrawableBuilder {
  public static final int ANDROID_ACTIONBAR_ICON_SIZE_DP = 24;
  
  private int alpha = 255;
  
  private final Rect bounds = new Rect();
  
  private final Context context;
  
  private IconValue icon = null;
  
  private MaterialDrawable mCachedDrawable;
  
  private TextPaint paint;
  
  private int size = -1;
  
  private MaterialDrawableBuilder(Context paramContext) {
    this.context = paramContext;
    this.paint = new TextPaint();
    this.paint.setTypeface(MaterialIconUtils.getTypeFace(paramContext));
    this.paint.setStyle(Paint.Style.STROKE);
    this.paint.setTextAlign(Paint.Align.CENTER);
    this.paint.setUnderlineText(false);
    this.paint.setColor(-16777216);
    this.paint.setAntiAlias(true);
    setToActionbarSize();
    setColor(-16777216);
  }
  
  public static MaterialDrawableBuilder with(Context paramContext) {
    return new MaterialDrawableBuilder(paramContext);
  }
  
  public MaterialDrawable build() throws IconNotSetException {
    if (this.icon == null)
      throw new IconNotSetException(); 
    return new MaterialDrawable(this.context, this.icon, this.paint, this.size, this.alpha);
  }
  
  public MaterialDrawableBuilder clearColorFilter() {
    this.paint.setColorFilter(null);
    return this;
  }
  
  public int getOpacity() {
    return this.alpha;
  }
  
  public MaterialDrawableBuilder setAlpha(int paramInt) {
    this.alpha = paramInt;
    this.paint.setAlpha(paramInt);
    return this;
  }
  
  public MaterialDrawableBuilder setColor(int paramInt) {
    this.paint.setColor(paramInt);
    if (Color.alpha(paramInt) != 255)
      this.paint.setAlpha(Color.alpha(paramInt)); 
    return this;
  }
  
  public MaterialDrawableBuilder setColorFilter(ColorFilter paramColorFilter) {
    this.paint.setColorFilter(paramColorFilter);
    return this;
  }
  
  public MaterialDrawableBuilder setColorResource(int paramInt) {
    setColor(this.context.getResources().getColor(paramInt));
    return this;
  }
  
  public MaterialDrawableBuilder setIcon(IconValue paramIconValue) {
    this.icon = paramIconValue;
    return this;
  }
  
  public MaterialDrawableBuilder setSizeDp(int paramInt) {
    return setSizePx(MaterialIconUtils.convertDpToPx(this.context, paramInt));
  }
  
  public MaterialDrawableBuilder setSizePx(int paramInt) {
    this.size = paramInt;
    this.bounds.set(0, 0, paramInt, paramInt);
    return this;
  }
  
  public MaterialDrawableBuilder setSizeResource(int paramInt) {
    return setSizePx(this.context.getResources().getDimensionPixelSize(paramInt));
  }
  
  public MaterialDrawableBuilder setStyle(Paint.Style paramStyle) {
    this.paint.setStyle(paramStyle);
    return this;
  }
  
  public MaterialDrawableBuilder setToActionbarSize() {
    return setSizeDp(24);
  }
  
  private class IconNotSetException extends RuntimeException {
    public IconNotSetException() {
      this("No icon provided when building MaterialDrawable.");
    }
    
    public IconNotSetException(String param1String) {
      super(param1String);
    }
    
    public IconNotSetException(String param1String, Throwable param1Throwable) {
      super(param1String, param1Throwable);
    }
    
    public IconNotSetException(Throwable param1Throwable) {
      super(param1Throwable);
    }
  }
  
  public enum IconValue {
    ACCOUNT, ACCOUNT_ALERT, ACCOUNT_BOX, ACCOUNT_BOX_OUTLINE, ACCOUNT_CHECK, ACCOUNT_CIRCLE, ACCOUNT_KEY, ACCOUNT_LOCATION, ACCOUNT_MINUS, ACCOUNT_MULTIPLE, ACCOUNT_MULTIPLE_OUTLINE, ACCOUNT_MULTIPLE_PLUS, ACCOUNT_NETWORK, ACCOUNT_OUTLINE, ACCOUNT_PLUS, ACCOUNT_REMOVE, ACCOUNT_SEARCH, ACCOUNT_STAR, ACCOUNT_STAR_VARIANT, ACCOUNT_SWITCH, AIRBALLOON, AIRPLANE, AIRPLANE_OFF, ALARM, ALARM_CHECK, ALARM_MULTIPLE, ALARM_OFF, ALARM_PLUS, ALBUM, ALERT, ALERT_BOX, ALERT_CIRCLE, ALERT_OCTAGON, ALPHA, ALPHABETICAL, AMAZON, AMAZON_CLOUDDRIVE, AMBULANCE, ANDROID, ANDROID_DEBUG_BRIDGE, ANDROID_STUDIO, APPLE, APPLE_FINDER, APPLE_MOBILEME, APPLE_SAFARI, APPNET, APPS, ARCHIVE, ARRANGE_BRING_FORWARD, ARRANGE_BRING_TO_FRONT, ARRANGE_SEND_BACKWARD, ARRANGE_SEND_TO_BACK, ARROW_ALL, ARROW_BOTTOM_LEFT, ARROW_BOTTOM_RIGHT, ARROW_COLLAPSE, ARROW_DOWN, ARROW_DOWN_BOLD, ARROW_DOWN_BOLD_CIRCLE, ARROW_DOWN_BOLD_CIRCLE_OUTLINE, ARROW_DOWN_BOLD_HEXAGON_OUTLINE, ARROW_EXPAND, ARROW_LEFT, ARROW_LEFT_BOLD, ARROW_LEFT_BOLD_CIRCLE, ARROW_LEFT_BOLD_CIRCLE_OUTLINE, ARROW_LEFT_BOLD_HEXAGON_OUTLINE, ARROW_RIGHT, ARROW_RIGHT_BOLD, ARROW_RIGHT_BOLD_CIRCLE, ARROW_RIGHT_BOLD_CIRCLE_OUTLINE, ARROW_RIGHT_BOLD_HEXAGON_OUTLINE, ARROW_TOP_LEFT, ARROW_TOP_RIGHT, ARROW_UP, ARROW_UP_BOLD, ARROW_UP_BOLD_CIRCLE, ARROW_UP_BOLD_CIRCLE_OUTLINE, ARROW_UP_BOLD_HEXAGON_OUTLINE, AT, ATTACHMENT, AUDIOBOOK, AUTO_FIX, AUTO_UPLOAD, BACKBURGER, BACKUP_RESTORE, BANK, BARCODE, BARLEY, BARREL, BASECAMP, BASKET, BASKET_FILL, BASKET_UNFILL, BATTERY, BATTERY_20, BATTERY_30, BATTERY_40, BATTERY_60, BATTERY_80, BATTERY_90, BATTERY_ALERT, BATTERY_CHARGING_100, BATTERY_CHARGING_20, BATTERY_CHARGING_30, BATTERY_CHARGING_40, BATTERY_CHARGING_60, BATTERY_CHARGING_80, BATTERY_CHARGING_90, BATTERY_MINUS, BATTERY_NEGATIVE, BATTERY_OUTLINE, BATTERY_PLUS, BATTERY_POSITIVE, BATTERY_UNKNOWN, BEACH, BEAKER, BEAKER_EMPTY, BEAKER_EMPTY_OUTLINE, BEAKER_OUTLINE, BEATS, BEER, BEHANCE, BELL, BELL_OFF, BELL_OUTLINE, BELL_RING, BELL_RING_OUTLINE, BELL_SLEEP, BETA, BIKE, BING, BINOCULARS, BIO, BIOHAZARD, BLACKBERRY, BLACK_MESA, BLINDS, BLOCK_HELPER, BLOGGER, BLUETOOTH, BLUETOOTH_AUDIO, BLUETOOTH_CONNECT, BLUETOOTH_SETTINGS, BLUR, BLUR_LINEAR, BLUR_OFF, BLUR_RADIAL, BONE, BOOK, BOOKMARK, BOOKMARK_CHECK, BOOKMARK_MUSIC, BOOKMARK_OUTLINE, BOOKMARK_OUTLINE_PLUS, BOOKMARK_PLUS, BOOKMARK_REMOVE, BOOK_MULTIPLE, BOOK_MULTIPLE_VARIANT, BOOK_OPEN, BOOK_VARIANT, BORDER_ALL, BORDER_BOTTOM, BORDER_COLOR, BORDER_HORIZONTAL, BORDER_INSIDE, BORDER_LEFT, BORDER_NONE, BORDER_OUTSIDE, BORDER_RIGHT, BORDER_TOP, BORDER_VERTICAL, BOWLING, BOX, BRIEFCASE, BRIEFCASE_CHECK, BRIEFCASE_DOWNLOAD, BRIEFCASE_UPLOAD, BRIGHTNESS_1, BRIGHTNESS_2, BRIGHTNESS_3, BRIGHTNESS_4, BRIGHTNESS_5, BRIGHTNESS_6, BRIGHTNESS_7, BRIGHTNESS_AUTO, BROOM, BRUSH, BUG, BULLHORN, BUS, CAKE, CAKE_VARIANT, CALCULATOR, CALENDAR, CALENDAR_BLANK, CALENDAR_CHECK, CALENDAR_CLOCK, CALENDAR_MULTIPLE, CALENDAR_MULTIPLE_CHECK, CALENDAR_PLUS, CALENDAR_REMOVE, CALENDAR_TEXT, CALENDAR_TODAY, CAMCORDER, CAMCORDER_BOX, CAMCORDER_BOX_OFF, CAMCORDER_OFF, CAMERA, CAMERA_IRIS, CAMERA_PARTY_MODE, CAMERA_SWITCH, CAMERA_TIMER, CANDYCANE, CAR, CARROT, CART, CART_OUTLINE, CAR_WASH, CASH, CASH_MULTIPLE, CASH_USD, CAST, CASTLE, CAST_CONNECTED, CAT, CELLPHONE, CELLPHONE_ANDROID, CELLPHONE_DOCK, CELLPHONE_IPHONE, CELLPHONE_LINK, CELLPHONE_LINK_OFF, CELLPHONE_SETTINGS, CHAIR_SCHOOL, CHART_ARC, CHART_AREASPLINE, CHART_BAR, CHART_HISTOGRAM, CHART_LINE, CHART_PIE, CHECK, CHECKBOX_BLANK, CHECKBOX_BLANK_CIRCLE, CHECKBOX_BLANK_CIRCLE_OUTLINE, CHECKBOX_BLANK_OUTLINE, CHECKBOX_MARKED, CHECKBOX_MARKED_CIRCLE, CHECKBOX_MARKED_CIRCLE_OUTLINE, CHECKBOX_MARKED_OUTLINE, CHECKBOX_MULTIPLE_BLANK, CHECKBOX_MULTIPLE_BLANK_OUTLINE, CHECKBOX_MULTIPLE_MARKED, CHECKBOX_MULTIPLE_MARKED_OUTLINE, CHECKERBOARD, CHECK_ALL, CHEVRON_DOUBLE_DOWN, CHEVRON_DOUBLE_LEFT, CHEVRON_DOUBLE_RIGHT, CHEVRON_DOUBLE_UP, CHEVRON_DOWN, CHEVRON_LEFT, CHEVRON_RIGHT, CHEVRON_UP, CHURCH, CISCO_WEBEX, CITY, CLIPBOARD, CLIPBOARD_ACCOUNT, CLIPBOARD_ALERT, CLIPBOARD_ARROW_DOWN, CLIPBOARD_ARROW_LEFT, CLIPBOARD_CHECK, CLIPBOARD_OUTLINE, CLIPBOARD_TEXT, CLIPPY, CLOCK, CLOCK_FAST, CLOSE, CLOSED_CAPTION, CLOSE_BOX, CLOSE_BOX_OUTLINE, CLOSE_CIRCLE, CLOSE_CIRCLE_OUTLINE, CLOSE_NETWORK, CLOUD, CLOUD_CHECK, CLOUD_CIRCLE, CLOUD_DOWNLOAD, CLOUD_OUTLINE, CLOUD_OUTLINE_OFF, CLOUD_UPLOAD, CODEPEN, CODE_ARRAY, CODE_STRING, COFFEE, COFFEE_TO_GO, COIN, COLOR_HELPER, COMMENT, COMMENT_ACCOUNT, COMMENT_ACCOUNT_OUTLINE, COMMENT_ALERT, COMMENT_ALERT_OUTLINE, COMMENT_CHECK, COMMENT_CHECK_OUTLINE, COMMENT_MULTIPLE_OUTLINE, COMMENT_OUTLINE, COMMENT_PLUS_OUTLINE, COMMENT_PROCESSING, COMMENT_PROCESSING_OUTLINE, COMMENT_REMOVE_OUTLINE, COMMENT_TEXT, COMMENT_TEXT_OUTLINE, COMPARE, COMPASS, COMPASS_OUTLINE, CONSOLE, CONTENT_COPY, CONTENT_CUT, CONTENT_PASTE, CONTENT_SAVE, CONTENT_SAVE_ALL, CONTRAST, CONTRAST_BOX, CONTRAST_CIRCLE, COW, CREDIT_CARD, CREDIT_CARD_MULTIPLE, CROP, CROP_FREE, CROP_LANDSCAPE, CROP_PORTRAIT, CROP_SQUARE, CROSSHAIRS, CROSSHAIRS_GPS, CROWN, CUBE, CUBE_OUTLINE, CUBE_UNFOLDED, CUP, CUP_WATER, CURRENCY_BTC, CURRENCY_EUR, CURRENCY_GBP, CURRENCY_INR, CURRENCY_RUB, CURRENCY_TRY, CURRENCY_USD, CURSOR_DEFAULT, CURSOR_DEFAULT_OUTLINE, CURSOR_MOVE, CURSOR_POINTER, DATABASE, DATABASE_MINUS, DATABASE_OUTLINE, DATABASE_PLUS, DEBUG_STEP_INTO, DEBUG_STEP_OUT, DEBUG_STEP_OVER, DELETE, DELETE_VARIANT, DESKPHONE, DESKTOP_MAC, DESKTOP_TOWER, DETAILS, DEVIANTART, DICE, DICE_1, DICE_2, DICE_3, DICE_4, DICE_5, DICE_6, DIRECTIONS, DISK_ALERT, DISQUS, DISQUS_OUTLINE, DIVISION, DIVISION_BOX, DNS, DOMAIN, DOTS_HORIZONTAL, DOTS_VERTICAL, DOWNLOAD, DRAG, DRAG_HORIZONTAL, DRAG_VERTICAL, DRAWING, DRAWING_BOX, DRIBBBLE, DRIBBBLE_BOX, DRONE, DROPBOX, DUCK, DUMBBELL, EARTH, EARTH_OFF, EDGE, ELEVATION_DECLINE, ELEVATION_RISE, ELEVATOR, EMAIL, EMAIL_OPEN, EMAIL_OUTLINE, EMOTICON, EMOTICON_COOL, EMOTICON_DEVIL, EMOTICON_HAPPY, EMOTICON_NEUTRAL, EMOTICON_POOP, EMOTICON_SAD, EMOTICON_TONGUE, EQUAL, EQUAL_BOX, ERASER, ESCALATOR, ETSY, EVERNOTE, EXCLAMATION, EXIT_TO_APP, EXPORT, EYE, EYEDROPPER, EYEDROPPER_VARIANT, EYE_OFF, FACEBOOK, FACEBOOK_BOX, FACEBOOK_MESSENGER, FACTORY, FAN, FAST_FORWARD, FERRY, FILE, FILE_CLOUD, FILE_DELIMITED, FILE_DOCUMENT, FILE_DOCUMENT_BOX, FILE_EXCEL, FILE_EXCEL_BOX, FILE_FIND, FILE_IMAGE, FILE_IMAGE_BOX, FILE_MUSIC, FILE_OUTLINE, FILE_PDF, FILE_PDF_BOX, FILE_POWERPOINT, FILE_POWERPOINT_BOX, FILE_PRESENTATION_BOX, FILE_VIDEO, FILE_WORD, FILE_WORD_BOX, FILE_XML, FILM, FILMSTRIP, FILMSTRIP_OFF, FILTER, FILTER_OUTLINE, FILTER_REMOVE, FILTER_REMOVE_OUTLINE, FILTER_VARIANT, FIRE, FIREFOX, FISH, FLAG, FLAG_CHECKERED, FLAG_OUTLINE, FLAG_OUTLINE_VARIANT, FLAG_TRIANGLE, FLAG_VARIANT, FLASH, FLASHLIGHT, FLASHLIGHT_OFF, FLASH_AUTO, FLASH_OFF, FLATTR, FLIP_TO_BACK, FLIP_TO_FRONT, FLOPPY, FLOWER, FOLDER, FOLDER_ACCOUNT, FOLDER_DOWNLOAD, FOLDER_GOOGLE_DRIVE, FOLDER_IMAGE, FOLDER_LOCK, FOLDER_LOCK_OPEN, FOLDER_MOVE, FOLDER_MULTIPLE, FOLDER_MULTIPLE_IMAGE, FOLDER_MULTIPLE_OUTLINE, FOLDER_OUTLINE, FOLDER_PLUS, FOLDER_REMOVE, FOLDER_UPLOAD, FOOD, FOOD_APPLE, FOOD_VARIANT, FOOTBALL, FOOTBALL_HELMET, FORMAT_ALIGN_CENTER, FORMAT_ALIGN_JUSTIFY, FORMAT_ALIGN_LEFT, FORMAT_ALIGN_RIGHT, FORMAT_BOLD, FORMAT_CLEAR, FORMAT_COLOR_FILL, FORMAT_HEADER_1, FORMAT_HEADER_2, FORMAT_HEADER_3, FORMAT_HEADER_4, FORMAT_HEADER_5, FORMAT_HEADER_6, FORMAT_HEADER_POUND, FORMAT_INDENT_DECREASE, FORMAT_INDENT_INCREASE, FORMAT_ITALIC, FORMAT_LINE_SPACING, FORMAT_LIST_BULLETED, FORMAT_LIST_NUMBERS, FORMAT_PAINT, FORMAT_PARAGRAPH, FORMAT_QUOTE, FORMAT_SIZE, FORMAT_STRIKETHROUGH, FORMAT_SUBSCRIPT, FORMAT_SUPERSCRIPT, FORMAT_TEXT, FORMAT_TEXTDIRECTION_L_TO_R, FORMAT_TEXTDIRECTION_R_TO_L, FORMAT_UNDERLINE, FORUM, FORWARD, FOURSQUARE, FRIDGE, FULLSCREEN, FULLSCREEN_EXIT, FUNCTION, GAMEPAD, GAMEPAD_VARIANT, GAS_STATION, GAVEL, GENDER_FEMALE, GENDER_MALE, GENDER_MALE_FEMALE, GENDER_TRANSGENDER, GIFT, GITHUB_BOX, GITHUB_CIRCLE, GLASS_FLUTE, GLASS_MUG, GLASS_STANGE, GLASS_TULIP, GMAIL, GOOGLE, GOOGLE_CHROME, GOOGLE_CIRCLES, GOOGLE_CIRCLES_COMMUNITIES, GOOGLE_CIRCLES_EXTENDED, GOOGLE_CIRCLES_GROUP, GOOGLE_CONTROLLER, GOOGLE_CONTROLLER_OFF, GOOGLE_DRIVE, GOOGLE_EARTH, GOOGLE_GLASS, GOOGLE_MAPS, GOOGLE_PAGES, GOOGLE_PLAY, GOOGLE_PLUS, GOOGLE_PLUS_BOX, GRID, GRID_OFF, GUITAR_PICK, GUITAR_PICK_OUTLINE, HAND_POINTING_RIGHT, HANGER, HANGOUTS, HARDDISK, HEADPHONES, HEADPHONES_BOX, HEADPHONES_SETTINGS, HEADSET, HEADSET_DOCK, HEADSET_OFF, HEART, HEART_BOX, HEART_BOX_OUTLINE, HEART_BROKEN, HEART_OUTLINE, HELP, HELP_CIRCLE, HEXAGON, HEXAGON_OUTLINE, HISTORY, HOLOLENS, HOME, HOME_MODERN, HOME_VARIANT, HOPS, HOSPITAL, HOSPITAL_BUILDING, HOSPITAL_MARKER, HOTEL, HOUZZ, HOUZZ_BOX, HUMAN, HUMAN_CHILD, HUMAN_MALE_FEMALE, IMAGE_ALBUM, IMAGE_AREA, IMAGE_AREA_CLOSE, IMAGE_BROKEN, IMAGE_FILTER, IMAGE_FILTER_BLACK_WHITE, IMAGE_FILTER_CENTER_FOCUS, IMAGE_FILTER_DRAMA, IMAGE_FILTER_FRAMES, IMAGE_FILTER_HDR, IMAGE_FILTER_NONE, IMAGE_FILTER_TILT_SHIFT, IMAGE_FILTER_VINTAGE, IMPORT, INBOX, INFORMATION, INFORMATION_OUTLINE, INSTAGRAM, INSTAPAPER, INTERNET_EXPLORER, INVERT_COLORS, JIRA, KEG, KEY, KEYBOARD, KEYBOARD_BACKSPACE, KEYBOARD_CAPS, KEYBOARD_CLOSE, KEYBOARD_OFF, KEYBOARD_RETURN, KEYBOARD_TAB, KEYBOARD_VARIANT, KEY_CHANGE, KEY_MINUS, KEY_PLUS, KEY_REMOVE, KEY_VARIANT, LABEL, LABEL_OUTLINE, LANGUAGE_CSHARP, LANGUAGE_CSS3, LANGUAGE_HTML5, LANGUAGE_JAVASCRIPT, LANGUAGE_PYTHON, LANGUAGE_PYTHON_TEXT, LAPTOP, LAPTOP_CHROMEBOOK, LAPTOP_MAC, LAPTOP_WINDOWS, LASTFM, LAUNCH, LAYERS, LAYERS_OFF, LEAF, LIBRARY, LIBRARY_BOOKS, LIBRARY_MUSIC, LIBRARY_PLUS, LIGHTBULB, LIGHTBULB_OUTLINE, LINK, LINKEDIN, LINKEDIN_BOX, LINK_VARIANT, LINUX, LOCK, LOCK_OPEN, LOCK_OPEN_OUTLINE, LOCK_OUTLINE, LOGIN, LOGOUT, LOOKS, LOUPE, LUMX, MAGNIFY, MAGNIFY_MINUS, MAGNIFY_PLUS, MAP, MAP_MARKER, MAP_MARKER_CIRCLE, MAP_MARKER_MULTIPLE, MAP_MARKER_OFF, MAP_MARKER_RADIUS, MARGIN, MARKDOWN, MARKER_CHECK, MARTINI, MATERIAL_UI, MATH_COMPASS, MAXCDN, MEMORY, MENU, MENU_DOWN, MENU_LEFT, MENU_RIGHT, MENU_UP, MESSAGE, MESSAGE_ALERT, MESSAGE_DRAW, MESSAGE_IMAGE, MESSAGE_PROCESSING, MESSAGE_REPLY, MESSAGE_TEXT, MESSAGE_TEXT_OUTLINE, MESSAGE_VIDEO, MICROPHONE, MICROPHONE_OFF, MICROPHONE_OUTLINE, MICROPHONE_SETTINGS, MICROPHONE_VARIANT, MICROPHONE_VARIANT_OFF, MINUS, MINUS_BOX, MINUS_CIRCLE, MINUS_CIRCLE_OUTLINE, MINUS_NETWORK, MONITOR, MONITOR_MULTIPLE, MORE, MOTORBIKE, MOUSE, MOUSE_OFF, MOUSE_VARIANT, MOUSE_VARIANT_OFF, MOVIE, MULTIPLICATION, MULTIPLICATION_BOX, MUSIC_BOX, MUSIC_BOX_OUTLINE, MUSIC_CIRCLE, MUSIC_NOTE, MUSIC_NOTE_EIGHTH, MUSIC_NOTE_HALF, MUSIC_NOTE_OFF, MUSIC_NOTE_QUARTER, MUSIC_NOTE_SIXTEENTH, MUSIC_NOTE_WHOLE, NATURE, NATURE_PEOPLE, NAVIGATION, NEEDLE, NEST_PROTECT, NEST_THERMOSTAT, NEWSPAPER, NFC, NFC_TAP, NFC_VARIANT, NUMERIC, NUMERIC_0_BOX, NUMERIC_0_BOX_MULTIPLE_OUTLINE, NUMERIC_0_BOX_OUTLINE, NUMERIC_1_BOX, NUMERIC_1_BOX_MULTIPLE_OUTLINE, NUMERIC_1_BOX_OUTLINE, NUMERIC_2_BOX, NUMERIC_2_BOX_MULTIPLE_OUTLINE, NUMERIC_2_BOX_OUTLINE, NUMERIC_3_BOX, NUMERIC_3_BOX_MULTIPLE_OUTLINE, NUMERIC_3_BOX_OUTLINE, NUMERIC_4_BOX, NUMERIC_4_BOX_MULTIPLE_OUTLINE, NUMERIC_4_BOX_OUTLINE, NUMERIC_5_BOX, NUMERIC_5_BOX_MULTIPLE_OUTLINE, NUMERIC_5_BOX_OUTLINE, NUMERIC_6_BOX, NUMERIC_6_BOX_MULTIPLE_OUTLINE, NUMERIC_6_BOX_OUTLINE, NUMERIC_7_BOX, NUMERIC_7_BOX_MULTIPLE_OUTLINE, NUMERIC_7_BOX_OUTLINE, NUMERIC_8_BOX, NUMERIC_8_BOX_MULTIPLE_OUTLINE, NUMERIC_8_BOX_OUTLINE, NUMERIC_9_BOX, NUMERIC_9_BOX_MULTIPLE_OUTLINE, NUMERIC_9_BOX_OUTLINE, NUMERIC_9_PLUS_BOX, NUMERIC_9_PLUS_BOX_MULTIPLE_OUTLINE, NUMERIC_9_PLUS_BOX_OUTLINE, NUTRITON, OFFICE, OIL, OMEGA, ONEDRIVE, OPEN_IN_APP, OPEN_IN_NEW, ORNAMENT, ORNAMENT_VARIANT, OUTBOX, PACKAGE, PACKAGE_DOWN, PACKAGE_UP, PACKAGE_VARIANT, PACKAGE_VARIANT_CLOSED, PALETTE, PALETTE_ADVANCED, PANDA, PANDORA, PANORAMA, PANORAMA_FISHEYE, PANORAMA_HORIZONTAL, PANORAMA_VERTICAL, PANORAMA_WIDE_ANGLE, PAPERCLIP, PAPER_CUT_VERTICAL, PARKING, PAUSE, PAUSE_CIRCLE, PAUSE_CIRCLE_OUTLINE, PAUSE_OCTAGON, PAUSE_OCTAGON_OUTLINE, PEN, PENCIL, PENCIL_BOX, PENCIL_BOX_OUTLINE, PHARMACY, PHONE, PHONE_BLUETOOTH, PHONE_FORWARD, PHONE_HANGUP, PHONE_IN_TALK, PHONE_LOCKED, PHONE_MISSED, PHONE_PAUSED, PHONE_SETTINGS, PIG, PILL, PIN, PINE_TREE, PINE_TREE_BOX, PINTEREST, PINTEREST_BOX, PIN_OFF, PIZZA, PLAY, PLAYLIST_MINUS, PLAYLIST_PLUS, PLAYSTATION, PLAY_BOX_OUTLINE, PLAY_CIRCLE, PLAY_CIRCLE_OUTLINE, PLUS, PLUS_BOX, PLUS_CIRCLE, PLUS_CIRCLE_OUTLINE, PLUS_NETWORK, PLUS_ONE, POCKET, POLL, POLL_BOX, POLYMER, POPCORN, POUND, POUND_BOX, POWER, POWER_SETTINGS, PRESENTATION, PRESENTATION_PLAY, PRINTER, PRINTER_3D, PULSE, PUZZLE, QRCODE, QUADCOPTER, QUALITY_HIGH, QUICKTIME, RADIATOR, RADIO, RADIOACTIVE, RADIOBOX_BLANK, RADIOBOX_MARKED, RADIO_TOWER, RASPBERRYPI, RDIO, READ, READABILITY, RECEIPT, RECYCLE, REDO, REDO_VARIANT, REFRESH, RELATIVE_SCALE, RELOAD, REMOTE, RENAME_BOX, REPEAT, REPEAT_OFF, REPEAT_ONCE, REPLAY, REPLY, REPLY_ALL, REPRODUCTION, RESIZE_BOTTOM_RIGHT, RESPONSIVE, REWIND, RIBBON, ROCKET, ROTATE_3D, ROTATE_LEFT, ROTATE_LEFT_VARIANT, ROTATE_RIGHT, ROTATE_RIGHT_VARIANT, ROUTES, RSS, RSS_BOX, RULER, RUN, SATELLITE, SATELLITE_VARIANT, SCALE, SCALE_BATHROOM, SCHOOL, SCREEN_ROTATION, SCREEN_ROTATION_LOCK, SCRIPT, SD, SECURITY, SECURITY_NETWORK, SELECT, SELECT_ALL, SELECT_INVERSE, SELECT_OFF, SEND, SERVER, SERVER_MINUS, SERVER_NETWORK, SERVER_NETWORK_OFF, SERVER_OFF, SERVER_PLUS, SERVER_REMOVE, SERVER_SECURITY, SETTINGS, SETTINGS_BOX, SHAPE_PLUS, SHARE, SHARE_VARIANT, SHIELD, SHIELD_OUTLINE, SHOPPING, SHOPPING_MUSIC, SHUFFLE, SIGMA, SIGN_CAUTION, SILVERWARE, SILVERWARE_FORK, SILVERWARE_SPOON, SILVERWARE_VARIANT, SIM_ALERT, SKIP_NEXT, SKIP_PREVIOUS, SNAPCHAT, SNOWMAN, SORT, SORT_ALPHABETICAL, SORT_ASCENDING, SORT_DESCENDING, SORT_NUMERIC, SORT_VARIANT, SOUNDCLOUD, SOURCE_FORK, SOURCE_PULL, SPEAKER, SPEAKER_OFF, SPEEDOMETER, SPELLCHECK, SPOTIFY, SPOTLIGHT, SPOTLIGHT_BEAM, STACKOVERFLOW, STAR, STAR_CIRCLE, STAR_HALF, STAR_OUTLINE, STOCKING, STOP, STORE, STORE_24_HOUR, STOVE, SUBWAY, SWAP_HORIZONTAL, SWAP_VERTICAL, SWIM, SWORD, SYNC, SYNC_ALERT, SYNC_OFF, TAB, TABLE, TABLET, TABLET_ANDROID, TABLET_IPAD, TABLE_COLUMN_PLUS_AFTER, TABLE_COLUMN_PLUS_BEFORE, TABLE_COLUMN_REMOVE, TABLE_COLUMN_WIDTH, TABLE_EDIT, TABLE_LARGE, TABLE_ROW_HEIGHT, TABLE_ROW_PLUS_AFTER, TABLE_ROW_PLUS_BEFORE, TABLE_ROW_REMOVE, TAB_UNSELECTED, TAG, TAG_FACES, TAG_MULTIPLE, TAG_OUTLINE, TAG_TEXT_OUTLINE, TAXI, TELEVISION, TELEVISION_GUIDE, TEMPERATURE_CELSIUS, TEMPERATURE_FAHRENHEIT, TEMPERATURE_KELVIN, TENT, TERRAIN, TEXTURE, TEXT_TO_SPEECH, TEXT_TO_SPEECH_OFF, THEATER, THEME_LIGHT_DARK, THERMOMETER, THERMOMETER_LINES, THUMBS_UP_DOWN, THUMB_DOWN, THUMB_DOWN_OUTLINE, THUMB_UP, THUMB_UP_OUTLINE, TICKET, TICKET_ACCOUNT, TIE, TIMELAPSE, TIMER, TIMER_10, TIMER_3, TIMER_OFF, TIMER_SAND, TIMETABLE, TOGGLE_SWITCH, TOGGLE_SWITCH_OFF, TOOLTIP, TOOLTIP_EDIT, TOOLTIP_IMAGE, TOOLTIP_OUTLINE, TOOLTIP_OUTLINE_PLUS, TOOLTIP_TEXT, TOR, TRAFFIC_LIGHT, TRAIN, TRAM, TRANSCRIBE, TRANSCRIBE_CLOSE, TRANSFER, TREE, TRELLO, TRENDING_DOWN, TRENDING_NEUTRAL, TRENDING_UP, TROPHY, TROPHY_AWARD, TROPHY_VARIANT, TRUCK, TSHIRT_CREW, TSHIRT_V, TUMBLR, TUMBLR_REBLOG, TWITCH, TWITTER, TWITTER_BOX, TWITTER_RETWEET, UBUNTU, UNDO, UNDO_VARIANT, UNFOLD_LESS, UNFOLD_MORE, UNTAPPD, UPLOAD, USB, VECTOR_CURVE, VECTOR_POINT, VECTOR_SQUARE, VERIFIED, VIBRATE, VIDEO, VIDEO_OFF, VIDEO_SWITCH, VIEW_AGENDA, VIEW_ARRAY, VIEW_CAROUSEL, VIEW_COLUMN, VIEW_DASHBOARD, VIEW_DAY, VIEW_HEADLINE, VIEW_LIST, VIEW_MODULE, VIEW_QUILT, VIEW_STREAM, VIEW_WEEK, VIMEO, VK, VOICEMAIL, VOLUME_HIGH, VOLUME_LOW, VOLUME_MEDIUM, VOLUME_OFF, WALK, WALLET, WALLET_GIFTCARD, WALLET_MEMBERSHIP, WALLET_TRAVEL, WATCH, WATCH_EXPORT, WATCH_IMPORT, WATER, WATER_OFF, WATER_PUMP, WEATHER_CLOUDY, WEATHER_HAIL, WEATHER_LIGHTNING, WEATHER_NIGHT, WEATHER_PARTLYCLOUDY, WEATHER_POURING, WEATHER_RAINY, WEATHER_SNOWY, WEATHER_SUNNY, WEATHER_SUNSET, WEATHER_SUNSET_DOWN, WEATHER_SUNSET_UP, WEATHER_WINDY, WEATHER_WINDY_VARIANT, WEB, WEBCAM, WEIGHT, WEIGHT_KILOGRAM, WHATSAPP, WHEELCHAIR_ACCESSIBILITY, WHITE_BALANCE_AUTO, WHITE_BALANCE_INCANDESCENT, WHITE_BALANCE_IRRADESCENT, WHITE_BALANCE_SUNNY, WIFI, WII, WIKIPEDIA, WINDOWS, WINDOW_CLOSE, WINDOW_CLOSED, WINDOW_MAXIMIZE, WINDOW_MINIMIZE, WINDOW_OPEN, WINDOW_RESTORE, WORDPRESS, WORKER, WUNDERLIST, XBOX, XBOX_CONTROLLER, XBOX_CONTROLLER_OFF, XDA, XML, YEAST, YOUTUBE_PLAY, ZIP_BOX;
    
    static {
      BOOKMARK = new IconValue("BOOKMARK", 154);
      BOOKMARK_CHECK = new IconValue("BOOKMARK_CHECK", 155);
      BOOKMARK_MUSIC = new IconValue("BOOKMARK_MUSIC", 156);
      BOOKMARK_OUTLINE = new IconValue("BOOKMARK_OUTLINE", 157);
      BOOKMARK_OUTLINE_PLUS = new IconValue("BOOKMARK_OUTLINE_PLUS", 158);
      BOOKMARK_PLUS = new IconValue("BOOKMARK_PLUS", 159);
      BOOKMARK_REMOVE = new IconValue("BOOKMARK_REMOVE", 160);
      BORDER_ALL = new IconValue("BORDER_ALL", 161);
      BORDER_BOTTOM = new IconValue("BORDER_BOTTOM", 162);
      BORDER_COLOR = new IconValue("BORDER_COLOR", 163);
      BORDER_HORIZONTAL = new IconValue("BORDER_HORIZONTAL", 164);
      BORDER_INSIDE = new IconValue("BORDER_INSIDE", 165);
      BORDER_LEFT = new IconValue("BORDER_LEFT", 166);
      BORDER_NONE = new IconValue("BORDER_NONE", 167);
      BORDER_OUTSIDE = new IconValue("BORDER_OUTSIDE", 168);
      BORDER_RIGHT = new IconValue("BORDER_RIGHT", 169);
      BORDER_TOP = new IconValue("BORDER_TOP", 170);
      BORDER_VERTICAL = new IconValue("BORDER_VERTICAL", 171);
      BOWLING = new IconValue("BOWLING", 172);
      BOX = new IconValue("BOX", 173);
      BRIEFCASE = new IconValue("BRIEFCASE", 174);
      BRIEFCASE_CHECK = new IconValue("BRIEFCASE_CHECK", 175);
      BRIEFCASE_DOWNLOAD = new IconValue("BRIEFCASE_DOWNLOAD", 176);
      BRIEFCASE_UPLOAD = new IconValue("BRIEFCASE_UPLOAD", 177);
      BRIGHTNESS_1 = new IconValue("BRIGHTNESS_1", 178);
      BRIGHTNESS_2 = new IconValue("BRIGHTNESS_2", 179);
      BRIGHTNESS_3 = new IconValue("BRIGHTNESS_3", 180);
      BRIGHTNESS_4 = new IconValue("BRIGHTNESS_4", 181);
      BRIGHTNESS_5 = new IconValue("BRIGHTNESS_5", 182);
      BRIGHTNESS_6 = new IconValue("BRIGHTNESS_6", 183);
      BRIGHTNESS_7 = new IconValue("BRIGHTNESS_7", 184);
      BRIGHTNESS_AUTO = new IconValue("BRIGHTNESS_AUTO", 185);
      BROOM = new IconValue("BROOM", 186);
      BRUSH = new IconValue("BRUSH", 187);
      BUG = new IconValue("BUG", 188);
      BULLHORN = new IconValue("BULLHORN", 189);
      BUS = new IconValue("BUS", 190);
      CAKE = new IconValue("CAKE", 191);
      CAKE_VARIANT = new IconValue("CAKE_VARIANT", 192);
      CALCULATOR = new IconValue("CALCULATOR", 193);
      CALENDAR = new IconValue("CALENDAR", 194);
      CALENDAR_BLANK = new IconValue("CALENDAR_BLANK", 195);
      CALENDAR_CHECK = new IconValue("CALENDAR_CHECK", 196);
      CALENDAR_CLOCK = new IconValue("CALENDAR_CLOCK", 197);
      CALENDAR_MULTIPLE = new IconValue("CALENDAR_MULTIPLE", 198);
      CALENDAR_MULTIPLE_CHECK = new IconValue("CALENDAR_MULTIPLE_CHECK", 199);
      CALENDAR_PLUS = new IconValue("CALENDAR_PLUS", 200);
      CALENDAR_REMOVE = new IconValue("CALENDAR_REMOVE", 201);
      CALENDAR_TEXT = new IconValue("CALENDAR_TEXT", 202);
      CALENDAR_TODAY = new IconValue("CALENDAR_TODAY", 203);
      CAMCORDER = new IconValue("CAMCORDER", 204);
      CAMCORDER_BOX = new IconValue("CAMCORDER_BOX", 205);
      CAMCORDER_BOX_OFF = new IconValue("CAMCORDER_BOX_OFF", 206);
      CAMCORDER_OFF = new IconValue("CAMCORDER_OFF", 207);
      CAMERA = new IconValue("CAMERA", 208);
      CAMERA_IRIS = new IconValue("CAMERA_IRIS", 209);
      CAMERA_PARTY_MODE = new IconValue("CAMERA_PARTY_MODE", 210);
      CAMERA_SWITCH = new IconValue("CAMERA_SWITCH", 211);
      CAMERA_TIMER = new IconValue("CAMERA_TIMER", 212);
      CANDYCANE = new IconValue("CANDYCANE", 213);
      CAR = new IconValue("CAR", 214);
      CAR_WASH = new IconValue("CAR_WASH", 215);
      CARROT = new IconValue("CARROT", 216);
      CART = new IconValue("CART", 217);
      CART_OUTLINE = new IconValue("CART_OUTLINE", 218);
      CASH = new IconValue("CASH", 219);
      CASH_MULTIPLE = new IconValue("CASH_MULTIPLE", 220);
      CASH_USD = new IconValue("CASH_USD", 221);
      CAST = new IconValue("CAST", 222);
      CAST_CONNECTED = new IconValue("CAST_CONNECTED", 223);
      CASTLE = new IconValue("CASTLE", 224);
      CAT = new IconValue("CAT", 225);
      CELLPHONE = new IconValue("CELLPHONE", 226);
      CELLPHONE_ANDROID = new IconValue("CELLPHONE_ANDROID", 227);
      CELLPHONE_DOCK = new IconValue("CELLPHONE_DOCK", 228);
      CELLPHONE_IPHONE = new IconValue("CELLPHONE_IPHONE", 229);
      CELLPHONE_LINK = new IconValue("CELLPHONE_LINK", 230);
      CELLPHONE_LINK_OFF = new IconValue("CELLPHONE_LINK_OFF", 231);
      CELLPHONE_SETTINGS = new IconValue("CELLPHONE_SETTINGS", 232);
      CHAIR_SCHOOL = new IconValue("CHAIR_SCHOOL", 233);
      CHART_ARC = new IconValue("CHART_ARC", 234);
      CHART_AREASPLINE = new IconValue("CHART_AREASPLINE", 235);
      CHART_BAR = new IconValue("CHART_BAR", 236);
      CHART_HISTOGRAM = new IconValue("CHART_HISTOGRAM", 237);
      CHART_LINE = new IconValue("CHART_LINE", 238);
      CHART_PIE = new IconValue("CHART_PIE", 239);
      CHECK = new IconValue("CHECK", 240);
      CHECK_ALL = new IconValue("CHECK_ALL", 241);
      CHECKBOX_BLANK = new IconValue("CHECKBOX_BLANK", 242);
      CHECKBOX_BLANK_CIRCLE = new IconValue("CHECKBOX_BLANK_CIRCLE", 243);
      CHECKBOX_BLANK_CIRCLE_OUTLINE = new IconValue("CHECKBOX_BLANK_CIRCLE_OUTLINE", 244);
      CHECKBOX_BLANK_OUTLINE = new IconValue("CHECKBOX_BLANK_OUTLINE", 245);
      CHECKBOX_MARKED = new IconValue("CHECKBOX_MARKED", 246);
      CHECKBOX_MARKED_CIRCLE = new IconValue("CHECKBOX_MARKED_CIRCLE", 247);
      CHECKBOX_MARKED_CIRCLE_OUTLINE = new IconValue("CHECKBOX_MARKED_CIRCLE_OUTLINE", 248);
      CHECKBOX_MARKED_OUTLINE = new IconValue("CHECKBOX_MARKED_OUTLINE", 249);
      CHECKBOX_MULTIPLE_BLANK = new IconValue("CHECKBOX_MULTIPLE_BLANK", 250);
      CHECKBOX_MULTIPLE_BLANK_OUTLINE = new IconValue("CHECKBOX_MULTIPLE_BLANK_OUTLINE", 251);
      CHECKBOX_MULTIPLE_MARKED = new IconValue("CHECKBOX_MULTIPLE_MARKED", 252);
      CHECKBOX_MULTIPLE_MARKED_OUTLINE = new IconValue("CHECKBOX_MULTIPLE_MARKED_OUTLINE", 253);
      CHECKERBOARD = new IconValue("CHECKERBOARD", 254);
      CHEVRON_DOUBLE_DOWN = new IconValue("CHEVRON_DOUBLE_DOWN", 255);
      CHEVRON_DOUBLE_LEFT = new IconValue("CHEVRON_DOUBLE_LEFT", 256);
      CHEVRON_DOUBLE_RIGHT = new IconValue("CHEVRON_DOUBLE_RIGHT", 257);
      CHEVRON_DOUBLE_UP = new IconValue("CHEVRON_DOUBLE_UP", 258);
      CHEVRON_DOWN = new IconValue("CHEVRON_DOWN", 259);
      CHEVRON_LEFT = new IconValue("CHEVRON_LEFT", 260);
      CHEVRON_RIGHT = new IconValue("CHEVRON_RIGHT", 261);
      CHEVRON_UP = new IconValue("CHEVRON_UP", 262);
      CHURCH = new IconValue("CHURCH", 263);
      CISCO_WEBEX = new IconValue("CISCO_WEBEX", 264);
      CITY = new IconValue("CITY", 265);
      CLIPBOARD = new IconValue("CLIPBOARD", 266);
      CLIPBOARD_ACCOUNT = new IconValue("CLIPBOARD_ACCOUNT", 267);
      CLIPBOARD_ALERT = new IconValue("CLIPBOARD_ALERT", 268);
      CLIPBOARD_ARROW_DOWN = new IconValue("CLIPBOARD_ARROW_DOWN", 269);
      CLIPBOARD_ARROW_LEFT = new IconValue("CLIPBOARD_ARROW_LEFT", 270);
      CLIPBOARD_CHECK = new IconValue("CLIPBOARD_CHECK", 271);
      CLIPBOARD_OUTLINE = new IconValue("CLIPBOARD_OUTLINE", 272);
      CLIPBOARD_TEXT = new IconValue("CLIPBOARD_TEXT", 273);
      CLIPPY = new IconValue("CLIPPY", 274);
      CLOCK = new IconValue("CLOCK", 275);
      CLOCK_FAST = new IconValue("CLOCK_FAST", 276);
      CLOSE = new IconValue("CLOSE", 277);
      CLOSE_BOX = new IconValue("CLOSE_BOX", 278);
      CLOSE_BOX_OUTLINE = new IconValue("CLOSE_BOX_OUTLINE", 279);
      CLOSE_CIRCLE = new IconValue("CLOSE_CIRCLE", 280);
      CLOSE_CIRCLE_OUTLINE = new IconValue("CLOSE_CIRCLE_OUTLINE", 281);
      CLOSE_NETWORK = new IconValue("CLOSE_NETWORK", 282);
      CLOSED_CAPTION = new IconValue("CLOSED_CAPTION", 283);
      CLOUD = new IconValue("CLOUD", 284);
      CLOUD_CHECK = new IconValue("CLOUD_CHECK", 285);
      CLOUD_CIRCLE = new IconValue("CLOUD_CIRCLE", 286);
      CLOUD_DOWNLOAD = new IconValue("CLOUD_DOWNLOAD", 287);
      CLOUD_OUTLINE = new IconValue("CLOUD_OUTLINE", 288);
      CLOUD_OUTLINE_OFF = new IconValue("CLOUD_OUTLINE_OFF", 289);
      CLOUD_UPLOAD = new IconValue("CLOUD_UPLOAD", 290);
      CODE_ARRAY = new IconValue("CODE_ARRAY", 291);
      CODE_STRING = new IconValue("CODE_STRING", 292);
      CODEPEN = new IconValue("CODEPEN", 293);
      COFFEE = new IconValue("COFFEE", 294);
      COFFEE_TO_GO = new IconValue("COFFEE_TO_GO", 295);
      COIN = new IconValue("COIN", 296);
      COLOR_HELPER = new IconValue("COLOR_HELPER", 297);
      COMMENT = new IconValue("COMMENT", 298);
      COMMENT_ACCOUNT = new IconValue("COMMENT_ACCOUNT", 299);
      COMMENT_ACCOUNT_OUTLINE = new IconValue("COMMENT_ACCOUNT_OUTLINE", 300);
      COMMENT_ALERT = new IconValue("COMMENT_ALERT", 301);
      COMMENT_ALERT_OUTLINE = new IconValue("COMMENT_ALERT_OUTLINE", 302);
      COMMENT_CHECK = new IconValue("COMMENT_CHECK", 303);
      COMMENT_CHECK_OUTLINE = new IconValue("COMMENT_CHECK_OUTLINE", 304);
      COMMENT_MULTIPLE_OUTLINE = new IconValue("COMMENT_MULTIPLE_OUTLINE", 305);
      COMMENT_OUTLINE = new IconValue("COMMENT_OUTLINE", 306);
      COMMENT_PLUS_OUTLINE = new IconValue("COMMENT_PLUS_OUTLINE", 307);
      COMMENT_PROCESSING = new IconValue("COMMENT_PROCESSING", 308);
      COMMENT_PROCESSING_OUTLINE = new IconValue("COMMENT_PROCESSING_OUTLINE", 309);
      COMMENT_REMOVE_OUTLINE = new IconValue("COMMENT_REMOVE_OUTLINE", 310);
      COMMENT_TEXT = new IconValue("COMMENT_TEXT", 311);
      COMMENT_TEXT_OUTLINE = new IconValue("COMMENT_TEXT_OUTLINE", 312);
      COMPARE = new IconValue("COMPARE", 313);
      COMPASS = new IconValue("COMPASS", 314);
      COMPASS_OUTLINE = new IconValue("COMPASS_OUTLINE", 315);
      CONSOLE = new IconValue("CONSOLE", 316);
      CONTENT_COPY = new IconValue("CONTENT_COPY", 317);
      CONTENT_CUT = new IconValue("CONTENT_CUT", 318);
      CONTENT_PASTE = new IconValue("CONTENT_PASTE", 319);
      CONTENT_SAVE = new IconValue("CONTENT_SAVE", 320);
      CONTENT_SAVE_ALL = new IconValue("CONTENT_SAVE_ALL", 321);
      CONTRAST = new IconValue("CONTRAST", 322);
      CONTRAST_BOX = new IconValue("CONTRAST_BOX", 323);
      CONTRAST_CIRCLE = new IconValue("CONTRAST_CIRCLE", 324);
      COW = new IconValue("COW", 325);
      CREDIT_CARD = new IconValue("CREDIT_CARD", 326);
      CREDIT_CARD_MULTIPLE = new IconValue("CREDIT_CARD_MULTIPLE", 327);
      CROP = new IconValue("CROP", 328);
      CROP_FREE = new IconValue("CROP_FREE", 329);
      CROP_LANDSCAPE = new IconValue("CROP_LANDSCAPE", 330);
      CROP_PORTRAIT = new IconValue("CROP_PORTRAIT", 331);
      CROP_SQUARE = new IconValue("CROP_SQUARE", 332);
      CROSSHAIRS = new IconValue("CROSSHAIRS", 333);
      CROSSHAIRS_GPS = new IconValue("CROSSHAIRS_GPS", 334);
      CROWN = new IconValue("CROWN", 335);
      CUBE = new IconValue("CUBE", 336);
      CUBE_OUTLINE = new IconValue("CUBE_OUTLINE", 337);
      CUBE_UNFOLDED = new IconValue("CUBE_UNFOLDED", 338);
      CUP = new IconValue("CUP", 339);
      CUP_WATER = new IconValue("CUP_WATER", 340);
      CURRENCY_BTC = new IconValue("CURRENCY_BTC", 341);
      CURRENCY_EUR = new IconValue("CURRENCY_EUR", 342);
      CURRENCY_GBP = new IconValue("CURRENCY_GBP", 343);
      CURRENCY_INR = new IconValue("CURRENCY_INR", 344);
      CURRENCY_RUB = new IconValue("CURRENCY_RUB", 345);
      CURRENCY_TRY = new IconValue("CURRENCY_TRY", 346);
      CURRENCY_USD = new IconValue("CURRENCY_USD", 347);
      CURSOR_DEFAULT = new IconValue("CURSOR_DEFAULT", 348);
      CURSOR_DEFAULT_OUTLINE = new IconValue("CURSOR_DEFAULT_OUTLINE", 349);
      CURSOR_MOVE = new IconValue("CURSOR_MOVE", 350);
      CURSOR_POINTER = new IconValue("CURSOR_POINTER", 351);
      DATABASE = new IconValue("DATABASE", 352);
      DATABASE_MINUS = new IconValue("DATABASE_MINUS", 353);
      DATABASE_OUTLINE = new IconValue("DATABASE_OUTLINE", 354);
      DATABASE_PLUS = new IconValue("DATABASE_PLUS", 355);
      DEBUG_STEP_INTO = new IconValue("DEBUG_STEP_INTO", 356);
      DEBUG_STEP_OUT = new IconValue("DEBUG_STEP_OUT", 357);
      DEBUG_STEP_OVER = new IconValue("DEBUG_STEP_OVER", 358);
      DELETE = new IconValue("DELETE", 359);
      DELETE_VARIANT = new IconValue("DELETE_VARIANT", 360);
      DESKPHONE = new IconValue("DESKPHONE", 361);
      DESKTOP_MAC = new IconValue("DESKTOP_MAC", 362);
      DESKTOP_TOWER = new IconValue("DESKTOP_TOWER", 363);
      DETAILS = new IconValue("DETAILS", 364);
      DEVIANTART = new IconValue("DEVIANTART", 365);
      DICE = new IconValue("DICE", 366);
      DICE_1 = new IconValue("DICE_1", 367);
      DICE_2 = new IconValue("DICE_2", 368);
      DICE_3 = new IconValue("DICE_3", 369);
      DICE_4 = new IconValue("DICE_4", 370);
      DICE_5 = new IconValue("DICE_5", 371);
      DICE_6 = new IconValue("DICE_6", 372);
      DIRECTIONS = new IconValue("DIRECTIONS", 373);
      DISK_ALERT = new IconValue("DISK_ALERT", 374);
      DISQUS = new IconValue("DISQUS", 375);
      DISQUS_OUTLINE = new IconValue("DISQUS_OUTLINE", 376);
      DIVISION = new IconValue("DIVISION", 377);
      DIVISION_BOX = new IconValue("DIVISION_BOX", 378);
      DNS = new IconValue("DNS", 379);
      DOMAIN = new IconValue("DOMAIN", 380);
      DOTS_HORIZONTAL = new IconValue("DOTS_HORIZONTAL", 381);
      DOTS_VERTICAL = new IconValue("DOTS_VERTICAL", 382);
      DOWNLOAD = new IconValue("DOWNLOAD", 383);
      DRAG = new IconValue("DRAG", 384);
      DRAG_HORIZONTAL = new IconValue("DRAG_HORIZONTAL", 385);
      DRAG_VERTICAL = new IconValue("DRAG_VERTICAL", 386);
      DRAWING = new IconValue("DRAWING", 387);
      DRAWING_BOX = new IconValue("DRAWING_BOX", 388);
      DRIBBBLE = new IconValue("DRIBBBLE", 389);
      DRIBBBLE_BOX = new IconValue("DRIBBBLE_BOX", 390);
      DRONE = new IconValue("DRONE", 391);
      DROPBOX = new IconValue("DROPBOX", 392);
      DUCK = new IconValue("DUCK", 393);
      DUMBBELL = new IconValue("DUMBBELL", 394);
      EARTH = new IconValue("EARTH", 395);
      EARTH_OFF = new IconValue("EARTH_OFF", 396);
      EDGE = new IconValue("EDGE", 397);
      ELEVATION_DECLINE = new IconValue("ELEVATION_DECLINE", 398);
      ELEVATION_RISE = new IconValue("ELEVATION_RISE", 399);
      ELEVATOR = new IconValue("ELEVATOR", 400);
      EMAIL = new IconValue("EMAIL", 401);
      EMAIL_OPEN = new IconValue("EMAIL_OPEN", 402);
      EMAIL_OUTLINE = new IconValue("EMAIL_OUTLINE", 403);
      EMOTICON = new IconValue("EMOTICON", 404);
      EMOTICON_COOL = new IconValue("EMOTICON_COOL", 405);
      EMOTICON_DEVIL = new IconValue("EMOTICON_DEVIL", 406);
      EMOTICON_HAPPY = new IconValue("EMOTICON_HAPPY", 407);
      EMOTICON_NEUTRAL = new IconValue("EMOTICON_NEUTRAL", 408);
      EMOTICON_POOP = new IconValue("EMOTICON_POOP", 409);
      EMOTICON_SAD = new IconValue("EMOTICON_SAD", 410);
      EMOTICON_TONGUE = new IconValue("EMOTICON_TONGUE", 411);
      EQUAL = new IconValue("EQUAL", 412);
      EQUAL_BOX = new IconValue("EQUAL_BOX", 413);
      ERASER = new IconValue("ERASER", 414);
      ESCALATOR = new IconValue("ESCALATOR", 415);
      ETSY = new IconValue("ETSY", 416);
      EVERNOTE = new IconValue("EVERNOTE", 417);
      EXCLAMATION = new IconValue("EXCLAMATION", 418);
      EXIT_TO_APP = new IconValue("EXIT_TO_APP", 419);
      EXPORT = new IconValue("EXPORT", 420);
      EYE = new IconValue("EYE", 421);
      EYE_OFF = new IconValue("EYE_OFF", 422);
      EYEDROPPER = new IconValue("EYEDROPPER", 423);
      EYEDROPPER_VARIANT = new IconValue("EYEDROPPER_VARIANT", 424);
      FACEBOOK = new IconValue("FACEBOOK", 425);
      FACEBOOK_BOX = new IconValue("FACEBOOK_BOX", 426);
      FACEBOOK_MESSENGER = new IconValue("FACEBOOK_MESSENGER", 427);
      FACTORY = new IconValue("FACTORY", 428);
      FAN = new IconValue("FAN", 429);
      FAST_FORWARD = new IconValue("FAST_FORWARD", 430);
      FERRY = new IconValue("FERRY", 431);
      FILE = new IconValue("FILE", 432);
      FILE_CLOUD = new IconValue("FILE_CLOUD", 433);
      FILE_DELIMITED = new IconValue("FILE_DELIMITED", 434);
      FILE_DOCUMENT = new IconValue("FILE_DOCUMENT", 435);
      FILE_DOCUMENT_BOX = new IconValue("FILE_DOCUMENT_BOX", 436);
      FILE_EXCEL = new IconValue("FILE_EXCEL", 437);
      FILE_EXCEL_BOX = new IconValue("FILE_EXCEL_BOX", 438);
      FILE_FIND = new IconValue("FILE_FIND", 439);
      FILE_IMAGE = new IconValue("FILE_IMAGE", 440);
      FILE_IMAGE_BOX = new IconValue("FILE_IMAGE_BOX", 441);
      FILE_MUSIC = new IconValue("FILE_MUSIC", 442);
      FILE_OUTLINE = new IconValue("FILE_OUTLINE", 443);
      FILE_PDF = new IconValue("FILE_PDF", 444);
      FILE_PDF_BOX = new IconValue("FILE_PDF_BOX", 445);
      FILE_POWERPOINT = new IconValue("FILE_POWERPOINT", 446);
      FILE_POWERPOINT_BOX = new IconValue("FILE_POWERPOINT_BOX", 447);
      FILE_PRESENTATION_BOX = new IconValue("FILE_PRESENTATION_BOX", 448);
      FILE_VIDEO = new IconValue("FILE_VIDEO", 449);
      FILE_WORD = new IconValue("FILE_WORD", 450);
      FILE_WORD_BOX = new IconValue("FILE_WORD_BOX", 451);
      FILE_XML = new IconValue("FILE_XML", 452);
      FILM = new IconValue("FILM", 453);
      FILMSTRIP = new IconValue("FILMSTRIP", 454);
      FILMSTRIP_OFF = new IconValue("FILMSTRIP_OFF", 455);
      FILTER = new IconValue("FILTER", 456);
      FILTER_OUTLINE = new IconValue("FILTER_OUTLINE", 457);
      FILTER_REMOVE = new IconValue("FILTER_REMOVE", 458);
      FILTER_REMOVE_OUTLINE = new IconValue("FILTER_REMOVE_OUTLINE", 459);
      FILTER_VARIANT = new IconValue("FILTER_VARIANT", 460);
      FIRE = new IconValue("FIRE", 461);
      FIREFOX = new IconValue("FIREFOX", 462);
      FISH = new IconValue("FISH", 463);
      FLAG = new IconValue("FLAG", 464);
      FLAG_CHECKERED = new IconValue("FLAG_CHECKERED", 465);
      FLAG_OUTLINE = new IconValue("FLAG_OUTLINE", 466);
      FLAG_OUTLINE_VARIANT = new IconValue("FLAG_OUTLINE_VARIANT", 467);
      FLAG_TRIANGLE = new IconValue("FLAG_TRIANGLE", 468);
      FLAG_VARIANT = new IconValue("FLAG_VARIANT", 469);
      FLASH = new IconValue("FLASH", 470);
      FLASH_AUTO = new IconValue("FLASH_AUTO", 471);
      FLASH_OFF = new IconValue("FLASH_OFF", 472);
      FLASHLIGHT = new IconValue("FLASHLIGHT", 473);
      FLASHLIGHT_OFF = new IconValue("FLASHLIGHT_OFF", 474);
      FLATTR = new IconValue("FLATTR", 475);
      FLIP_TO_BACK = new IconValue("FLIP_TO_BACK", 476);
      FLIP_TO_FRONT = new IconValue("FLIP_TO_FRONT", 477);
      FLOPPY = new IconValue("FLOPPY", 478);
      FLOWER = new IconValue("FLOWER", 479);
      FOLDER = new IconValue("FOLDER", 480);
      FOLDER_ACCOUNT = new IconValue("FOLDER_ACCOUNT", 481);
      FOLDER_DOWNLOAD = new IconValue("FOLDER_DOWNLOAD", 482);
      FOLDER_GOOGLE_DRIVE = new IconValue("FOLDER_GOOGLE_DRIVE", 483);
      FOLDER_IMAGE = new IconValue("FOLDER_IMAGE", 484);
      FOLDER_LOCK = new IconValue("FOLDER_LOCK", 485);
      FOLDER_LOCK_OPEN = new IconValue("FOLDER_LOCK_OPEN", 486);
      FOLDER_MOVE = new IconValue("FOLDER_MOVE", 487);
      FOLDER_MULTIPLE = new IconValue("FOLDER_MULTIPLE", 488);
      FOLDER_MULTIPLE_IMAGE = new IconValue("FOLDER_MULTIPLE_IMAGE", 489);
      FOLDER_MULTIPLE_OUTLINE = new IconValue("FOLDER_MULTIPLE_OUTLINE", 490);
      FOLDER_OUTLINE = new IconValue("FOLDER_OUTLINE", 491);
      FOLDER_PLUS = new IconValue("FOLDER_PLUS", 492);
      FOLDER_REMOVE = new IconValue("FOLDER_REMOVE", 493);
      FOLDER_UPLOAD = new IconValue("FOLDER_UPLOAD", 494);
      FOOD = new IconValue("FOOD", 495);
      FOOD_APPLE = new IconValue("FOOD_APPLE", 496);
      FOOD_VARIANT = new IconValue("FOOD_VARIANT", 497);
      FOOTBALL = new IconValue("FOOTBALL", 498);
      FOOTBALL_HELMET = new IconValue("FOOTBALL_HELMET", 499);
      FORMAT_ALIGN_CENTER = new IconValue("FORMAT_ALIGN_CENTER", 500);
      FORMAT_ALIGN_JUSTIFY = new IconValue("FORMAT_ALIGN_JUSTIFY", 501);
      FORMAT_ALIGN_LEFT = new IconValue("FORMAT_ALIGN_LEFT", 502);
      FORMAT_ALIGN_RIGHT = new IconValue("FORMAT_ALIGN_RIGHT", 503);
      FORMAT_BOLD = new IconValue("FORMAT_BOLD", 504);
      FORMAT_CLEAR = new IconValue("FORMAT_CLEAR", 505);
      FORMAT_COLOR_FILL = new IconValue("FORMAT_COLOR_FILL", 506);
      FORMAT_HEADER_1 = new IconValue("FORMAT_HEADER_1", 507);
      FORMAT_HEADER_2 = new IconValue("FORMAT_HEADER_2", 508);
      FORMAT_HEADER_3 = new IconValue("FORMAT_HEADER_3", 509);
      FORMAT_HEADER_4 = new IconValue("FORMAT_HEADER_4", 510);
      FORMAT_HEADER_5 = new IconValue("FORMAT_HEADER_5", 511);
      FORMAT_HEADER_6 = new IconValue("FORMAT_HEADER_6", 512);
      FORMAT_HEADER_POUND = new IconValue("FORMAT_HEADER_POUND", 513);
      FORMAT_INDENT_DECREASE = new IconValue("FORMAT_INDENT_DECREASE", 514);
      FORMAT_INDENT_INCREASE = new IconValue("FORMAT_INDENT_INCREASE", 515);
      FORMAT_ITALIC = new IconValue("FORMAT_ITALIC", 516);
      FORMAT_LINE_SPACING = new IconValue("FORMAT_LINE_SPACING", 517);
      FORMAT_LIST_BULLETED = new IconValue("FORMAT_LIST_BULLETED", 518);
      FORMAT_LIST_NUMBERS = new IconValue("FORMAT_LIST_NUMBERS", 519);
      FORMAT_PAINT = new IconValue("FORMAT_PAINT", 520);
      FORMAT_PARAGRAPH = new IconValue("FORMAT_PARAGRAPH", 521);
      FORMAT_QUOTE = new IconValue("FORMAT_QUOTE", 522);
      FORMAT_SIZE = new IconValue("FORMAT_SIZE", 523);
      FORMAT_STRIKETHROUGH = new IconValue("FORMAT_STRIKETHROUGH", 524);
      FORMAT_SUBSCRIPT = new IconValue("FORMAT_SUBSCRIPT", 525);
      FORMAT_SUPERSCRIPT = new IconValue("FORMAT_SUPERSCRIPT", 526);
      FORMAT_TEXT = new IconValue("FORMAT_TEXT", 527);
      FORMAT_TEXTDIRECTION_L_TO_R = new IconValue("FORMAT_TEXTDIRECTION_L_TO_R", 528);
      FORMAT_TEXTDIRECTION_R_TO_L = new IconValue("FORMAT_TEXTDIRECTION_R_TO_L", 529);
      FORMAT_UNDERLINE = new IconValue("FORMAT_UNDERLINE", 530);
      FORUM = new IconValue("FORUM", 531);
      FORWARD = new IconValue("FORWARD", 532);
      FOURSQUARE = new IconValue("FOURSQUARE", 533);
      FRIDGE = new IconValue("FRIDGE", 534);
      FULLSCREEN = new IconValue("FULLSCREEN", 535);
      FULLSCREEN_EXIT = new IconValue("FULLSCREEN_EXIT", 536);
      FUNCTION = new IconValue("FUNCTION", 537);
      GAMEPAD = new IconValue("GAMEPAD", 538);
      GAMEPAD_VARIANT = new IconValue("GAMEPAD_VARIANT", 539);
      GAS_STATION = new IconValue("GAS_STATION", 540);
      GAVEL = new IconValue("GAVEL", 541);
      GENDER_FEMALE = new IconValue("GENDER_FEMALE", 542);
      GENDER_MALE = new IconValue("GENDER_MALE", 543);
      GENDER_MALE_FEMALE = new IconValue("GENDER_MALE_FEMALE", 544);
      GENDER_TRANSGENDER = new IconValue("GENDER_TRANSGENDER", 545);
      GIFT = new IconValue("GIFT", 546);
      GITHUB_BOX = new IconValue("GITHUB_BOX", 547);
      GITHUB_CIRCLE = new IconValue("GITHUB_CIRCLE", 548);
      GLASS_FLUTE = new IconValue("GLASS_FLUTE", 549);
      GLASS_MUG = new IconValue("GLASS_MUG", 550);
      GLASS_STANGE = new IconValue("GLASS_STANGE", 551);
      GLASS_TULIP = new IconValue("GLASS_TULIP", 552);
      GMAIL = new IconValue("GMAIL", 553);
      GOOGLE = new IconValue("GOOGLE", 554);
      GOOGLE_CHROME = new IconValue("GOOGLE_CHROME", 555);
      GOOGLE_CIRCLES = new IconValue("GOOGLE_CIRCLES", 556);
      GOOGLE_CIRCLES_COMMUNITIES = new IconValue("GOOGLE_CIRCLES_COMMUNITIES", 557);
      GOOGLE_CIRCLES_EXTENDED = new IconValue("GOOGLE_CIRCLES_EXTENDED", 558);
      GOOGLE_CIRCLES_GROUP = new IconValue("GOOGLE_CIRCLES_GROUP", 559);
      GOOGLE_CONTROLLER = new IconValue("GOOGLE_CONTROLLER", 560);
      GOOGLE_CONTROLLER_OFF = new IconValue("GOOGLE_CONTROLLER_OFF", 561);
      GOOGLE_DRIVE = new IconValue("GOOGLE_DRIVE", 562);
      GOOGLE_EARTH = new IconValue("GOOGLE_EARTH", 563);
      GOOGLE_GLASS = new IconValue("GOOGLE_GLASS", 564);
      GOOGLE_MAPS = new IconValue("GOOGLE_MAPS", 565);
      GOOGLE_PAGES = new IconValue("GOOGLE_PAGES", 566);
      GOOGLE_PLAY = new IconValue("GOOGLE_PLAY", 567);
      GOOGLE_PLUS = new IconValue("GOOGLE_PLUS", 568);
      GOOGLE_PLUS_BOX = new IconValue("GOOGLE_PLUS_BOX", 569);
      GRID = new IconValue("GRID", 570);
      GRID_OFF = new IconValue("GRID_OFF", 571);
      GUITAR_PICK = new IconValue("GUITAR_PICK", 572);
      GUITAR_PICK_OUTLINE = new IconValue("GUITAR_PICK_OUTLINE", 573);
      HAND_POINTING_RIGHT = new IconValue("HAND_POINTING_RIGHT", 574);
      HANGER = new IconValue("HANGER", 575);
      HANGOUTS = new IconValue("HANGOUTS", 576);
      HARDDISK = new IconValue("HARDDISK", 577);
      HEADPHONES = new IconValue("HEADPHONES", 578);
      HEADPHONES_BOX = new IconValue("HEADPHONES_BOX", 579);
      HEADPHONES_SETTINGS = new IconValue("HEADPHONES_SETTINGS", 580);
      HEADSET = new IconValue("HEADSET", 581);
      HEADSET_DOCK = new IconValue("HEADSET_DOCK", 582);
      HEADSET_OFF = new IconValue("HEADSET_OFF", 583);
      HEART = new IconValue("HEART", 584);
      HEART_BOX = new IconValue("HEART_BOX", 585);
      HEART_BOX_OUTLINE = new IconValue("HEART_BOX_OUTLINE", 586);
      HEART_BROKEN = new IconValue("HEART_BROKEN", 587);
      HEART_OUTLINE = new IconValue("HEART_OUTLINE", 588);
      HELP = new IconValue("HELP", 589);
      HELP_CIRCLE = new IconValue("HELP_CIRCLE", 590);
      HEXAGON = new IconValue("HEXAGON", 591);
      HEXAGON_OUTLINE = new IconValue("HEXAGON_OUTLINE", 592);
      HISTORY = new IconValue("HISTORY", 593);
      HOLOLENS = new IconValue("HOLOLENS", 594);
      HOME = new IconValue("HOME", 595);
      HOME_MODERN = new IconValue("HOME_MODERN", 596);
      HOME_VARIANT = new IconValue("HOME_VARIANT", 597);
      HOPS = new IconValue("HOPS", 598);
      HOSPITAL = new IconValue("HOSPITAL", 599);
      HOSPITAL_BUILDING = new IconValue("HOSPITAL_BUILDING", 600);
      HOSPITAL_MARKER = new IconValue("HOSPITAL_MARKER", 601);
      HOTEL = new IconValue("HOTEL", 602);
      HOUZZ = new IconValue("HOUZZ", 603);
      HOUZZ_BOX = new IconValue("HOUZZ_BOX", 604);
      HUMAN = new IconValue("HUMAN", 605);
      HUMAN_CHILD = new IconValue("HUMAN_CHILD", 606);
      HUMAN_MALE_FEMALE = new IconValue("HUMAN_MALE_FEMALE", 607);
      IMAGE_ALBUM = new IconValue("IMAGE_ALBUM", 608);
      IMAGE_AREA = new IconValue("IMAGE_AREA", 609);
      IMAGE_AREA_CLOSE = new IconValue("IMAGE_AREA_CLOSE", 610);
      IMAGE_BROKEN = new IconValue("IMAGE_BROKEN", 611);
      IMAGE_FILTER = new IconValue("IMAGE_FILTER", 612);
      IMAGE_FILTER_BLACK_WHITE = new IconValue("IMAGE_FILTER_BLACK_WHITE", 613);
      IMAGE_FILTER_CENTER_FOCUS = new IconValue("IMAGE_FILTER_CENTER_FOCUS", 614);
      IMAGE_FILTER_DRAMA = new IconValue("IMAGE_FILTER_DRAMA", 615);
      IMAGE_FILTER_FRAMES = new IconValue("IMAGE_FILTER_FRAMES", 616);
      IMAGE_FILTER_HDR = new IconValue("IMAGE_FILTER_HDR", 617);
      IMAGE_FILTER_NONE = new IconValue("IMAGE_FILTER_NONE", 618);
      IMAGE_FILTER_TILT_SHIFT = new IconValue("IMAGE_FILTER_TILT_SHIFT", 619);
      IMAGE_FILTER_VINTAGE = new IconValue("IMAGE_FILTER_VINTAGE", 620);
      IMPORT = new IconValue("IMPORT", 621);
      INBOX = new IconValue("INBOX", 622);
      INFORMATION = new IconValue("INFORMATION", 623);
      INFORMATION_OUTLINE = new IconValue("INFORMATION_OUTLINE", 624);
      INSTAGRAM = new IconValue("INSTAGRAM", 625);
      INSTAPAPER = new IconValue("INSTAPAPER", 626);
      INTERNET_EXPLORER = new IconValue("INTERNET_EXPLORER", 627);
      INVERT_COLORS = new IconValue("INVERT_COLORS", 628);
      JIRA = new IconValue("JIRA", 629);
      KEG = new IconValue("KEG", 630);
      KEY = new IconValue("KEY", 631);
      KEY_CHANGE = new IconValue("KEY_CHANGE", 632);
      KEY_MINUS = new IconValue("KEY_MINUS", 633);
      KEY_PLUS = new IconValue("KEY_PLUS", 634);
      KEY_REMOVE = new IconValue("KEY_REMOVE", 635);
      KEY_VARIANT = new IconValue("KEY_VARIANT", 636);
      KEYBOARD = new IconValue("KEYBOARD", 637);
      KEYBOARD_BACKSPACE = new IconValue("KEYBOARD_BACKSPACE", 638);
      KEYBOARD_CAPS = new IconValue("KEYBOARD_CAPS", 639);
      KEYBOARD_CLOSE = new IconValue("KEYBOARD_CLOSE", 640);
      KEYBOARD_OFF = new IconValue("KEYBOARD_OFF", 641);
      KEYBOARD_RETURN = new IconValue("KEYBOARD_RETURN", 642);
      KEYBOARD_TAB = new IconValue("KEYBOARD_TAB", 643);
      KEYBOARD_VARIANT = new IconValue("KEYBOARD_VARIANT", 644);
      LABEL = new IconValue("LABEL", 645);
      LABEL_OUTLINE = new IconValue("LABEL_OUTLINE", 646);
      LANGUAGE_CSHARP = new IconValue("LANGUAGE_CSHARP", 647);
      LANGUAGE_CSS3 = new IconValue("LANGUAGE_CSS3", 648);
      LANGUAGE_HTML5 = new IconValue("LANGUAGE_HTML5", 649);
      LANGUAGE_JAVASCRIPT = new IconValue("LANGUAGE_JAVASCRIPT", 650);
      LANGUAGE_PYTHON = new IconValue("LANGUAGE_PYTHON", 651);
      LANGUAGE_PYTHON_TEXT = new IconValue("LANGUAGE_PYTHON_TEXT", 652);
      LAPTOP = new IconValue("LAPTOP", 653);
      LAPTOP_CHROMEBOOK = new IconValue("LAPTOP_CHROMEBOOK", 654);
      LAPTOP_MAC = new IconValue("LAPTOP_MAC", 655);
      LAPTOP_WINDOWS = new IconValue("LAPTOP_WINDOWS", 656);
      LASTFM = new IconValue("LASTFM", 657);
      LAUNCH = new IconValue("LAUNCH", 658);
      LAYERS = new IconValue("LAYERS", 659);
      LAYERS_OFF = new IconValue("LAYERS_OFF", 660);
      LEAF = new IconValue("LEAF", 661);
      LIBRARY = new IconValue("LIBRARY", 662);
      LIBRARY_BOOKS = new IconValue("LIBRARY_BOOKS", 663);
      LIBRARY_MUSIC = new IconValue("LIBRARY_MUSIC", 664);
      LIBRARY_PLUS = new IconValue("LIBRARY_PLUS", 665);
      LIGHTBULB = new IconValue("LIGHTBULB", 666);
      LIGHTBULB_OUTLINE = new IconValue("LIGHTBULB_OUTLINE", 667);
      LINK = new IconValue("LINK", 668);
      LINK_VARIANT = new IconValue("LINK_VARIANT", 669);
      LINKEDIN = new IconValue("LINKEDIN", 670);
      LINKEDIN_BOX = new IconValue("LINKEDIN_BOX", 671);
      LINUX = new IconValue("LINUX", 672);
      LOCK = new IconValue("LOCK", 673);
      LOCK_OPEN = new IconValue("LOCK_OPEN", 674);
      LOCK_OPEN_OUTLINE = new IconValue("LOCK_OPEN_OUTLINE", 675);
      LOCK_OUTLINE = new IconValue("LOCK_OUTLINE", 676);
      LOGIN = new IconValue("LOGIN", 677);
      LOGOUT = new IconValue("LOGOUT", 678);
      LOOKS = new IconValue("LOOKS", 679);
      LOUPE = new IconValue("LOUPE", 680);
      LUMX = new IconValue("LUMX", 681);
      MAGNIFY = new IconValue("MAGNIFY", 682);
      MAGNIFY_MINUS = new IconValue("MAGNIFY_MINUS", 683);
      MAGNIFY_PLUS = new IconValue("MAGNIFY_PLUS", 684);
      MAP = new IconValue("MAP", 685);
      MAP_MARKER = new IconValue("MAP_MARKER", 686);
      MAP_MARKER_CIRCLE = new IconValue("MAP_MARKER_CIRCLE", 687);
      MAP_MARKER_MULTIPLE = new IconValue("MAP_MARKER_MULTIPLE", 688);
      MAP_MARKER_OFF = new IconValue("MAP_MARKER_OFF", 689);
      MAP_MARKER_RADIUS = new IconValue("MAP_MARKER_RADIUS", 690);
      MARGIN = new IconValue("MARGIN", 691);
      MARKDOWN = new IconValue("MARKDOWN", 692);
      MARKER_CHECK = new IconValue("MARKER_CHECK", 693);
      MARTINI = new IconValue("MARTINI", 694);
      MATERIAL_UI = new IconValue("MATERIAL_UI", 695);
      MATH_COMPASS = new IconValue("MATH_COMPASS", 696);
      MAXCDN = new IconValue("MAXCDN", 697);
      MEMORY = new IconValue("MEMORY", 698);
      MENU = new IconValue("MENU", 699);
      MENU_DOWN = new IconValue("MENU_DOWN", 700);
      MENU_LEFT = new IconValue("MENU_LEFT", 701);
      MENU_RIGHT = new IconValue("MENU_RIGHT", 702);
      MENU_UP = new IconValue("MENU_UP", 703);
      MESSAGE = new IconValue("MESSAGE", 704);
      MESSAGE_ALERT = new IconValue("MESSAGE_ALERT", 705);
      MESSAGE_DRAW = new IconValue("MESSAGE_DRAW", 706);
      MESSAGE_IMAGE = new IconValue("MESSAGE_IMAGE", 707);
      MESSAGE_PROCESSING = new IconValue("MESSAGE_PROCESSING", 708);
      MESSAGE_REPLY = new IconValue("MESSAGE_REPLY", 709);
      MESSAGE_TEXT = new IconValue("MESSAGE_TEXT", 710);
      MESSAGE_TEXT_OUTLINE = new IconValue("MESSAGE_TEXT_OUTLINE", 711);
      MESSAGE_VIDEO = new IconValue("MESSAGE_VIDEO", 712);
      MICROPHONE = new IconValue("MICROPHONE", 713);
      MICROPHONE_OFF = new IconValue("MICROPHONE_OFF", 714);
      MICROPHONE_OUTLINE = new IconValue("MICROPHONE_OUTLINE", 715);
      MICROPHONE_SETTINGS = new IconValue("MICROPHONE_SETTINGS", 716);
      MICROPHONE_VARIANT = new IconValue("MICROPHONE_VARIANT", 717);
      MICROPHONE_VARIANT_OFF = new IconValue("MICROPHONE_VARIANT_OFF", 718);
      MINUS = new IconValue("MINUS", 719);
      MINUS_BOX = new IconValue("MINUS_BOX", 720);
      MINUS_CIRCLE = new IconValue("MINUS_CIRCLE", 721);
      MINUS_CIRCLE_OUTLINE = new IconValue("MINUS_CIRCLE_OUTLINE", 722);
      MINUS_NETWORK = new IconValue("MINUS_NETWORK", 723);
      MONITOR = new IconValue("MONITOR", 724);
      MONITOR_MULTIPLE = new IconValue("MONITOR_MULTIPLE", 725);
      MORE = new IconValue("MORE", 726);
      MOTORBIKE = new IconValue("MOTORBIKE", 727);
      MOUSE = new IconValue("MOUSE", 728);
      MOUSE_OFF = new IconValue("MOUSE_OFF", 729);
      MOUSE_VARIANT = new IconValue("MOUSE_VARIANT", 730);
      MOUSE_VARIANT_OFF = new IconValue("MOUSE_VARIANT_OFF", 731);
      MOVIE = new IconValue("MOVIE", 732);
      MULTIPLICATION = new IconValue("MULTIPLICATION", 733);
      MULTIPLICATION_BOX = new IconValue("MULTIPLICATION_BOX", 734);
      MUSIC_BOX = new IconValue("MUSIC_BOX", 735);
      MUSIC_BOX_OUTLINE = new IconValue("MUSIC_BOX_OUTLINE", 736);
      MUSIC_CIRCLE = new IconValue("MUSIC_CIRCLE", 737);
      MUSIC_NOTE = new IconValue("MUSIC_NOTE", 738);
      MUSIC_NOTE_EIGHTH = new IconValue("MUSIC_NOTE_EIGHTH", 739);
      MUSIC_NOTE_HALF = new IconValue("MUSIC_NOTE_HALF", 740);
      MUSIC_NOTE_OFF = new IconValue("MUSIC_NOTE_OFF", 741);
      MUSIC_NOTE_QUARTER = new IconValue("MUSIC_NOTE_QUARTER", 742);
      MUSIC_NOTE_SIXTEENTH = new IconValue("MUSIC_NOTE_SIXTEENTH", 743);
      MUSIC_NOTE_WHOLE = new IconValue("MUSIC_NOTE_WHOLE", 744);
      NATURE = new IconValue("NATURE", 745);
      NATURE_PEOPLE = new IconValue("NATURE_PEOPLE", 746);
      NAVIGATION = new IconValue("NAVIGATION", 747);
      NEEDLE = new IconValue("NEEDLE", 748);
      NEST_PROTECT = new IconValue("NEST_PROTECT", 749);
      NEST_THERMOSTAT = new IconValue("NEST_THERMOSTAT", 750);
      NEWSPAPER = new IconValue("NEWSPAPER", 751);
      NFC = new IconValue("NFC", 752);
      NFC_TAP = new IconValue("NFC_TAP", 753);
      NFC_VARIANT = new IconValue("NFC_VARIANT", 754);
      NUMERIC = new IconValue("NUMERIC", 755);
      NUMERIC_0_BOX = new IconValue("NUMERIC_0_BOX", 756);
      NUMERIC_0_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_0_BOX_MULTIPLE_OUTLINE", 757);
      NUMERIC_0_BOX_OUTLINE = new IconValue("NUMERIC_0_BOX_OUTLINE", 758);
      NUMERIC_1_BOX = new IconValue("NUMERIC_1_BOX", 759);
      NUMERIC_1_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_1_BOX_MULTIPLE_OUTLINE", 760);
      NUMERIC_1_BOX_OUTLINE = new IconValue("NUMERIC_1_BOX_OUTLINE", 761);
      NUMERIC_2_BOX = new IconValue("NUMERIC_2_BOX", 762);
      NUMERIC_2_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_2_BOX_MULTIPLE_OUTLINE", 763);
      NUMERIC_2_BOX_OUTLINE = new IconValue("NUMERIC_2_BOX_OUTLINE", 764);
      NUMERIC_3_BOX = new IconValue("NUMERIC_3_BOX", 765);
      NUMERIC_3_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_3_BOX_MULTIPLE_OUTLINE", 766);
      NUMERIC_3_BOX_OUTLINE = new IconValue("NUMERIC_3_BOX_OUTLINE", 767);
      NUMERIC_4_BOX = new IconValue("NUMERIC_4_BOX", 768);
      NUMERIC_4_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_4_BOX_MULTIPLE_OUTLINE", 769);
      NUMERIC_4_BOX_OUTLINE = new IconValue("NUMERIC_4_BOX_OUTLINE", 770);
      NUMERIC_5_BOX = new IconValue("NUMERIC_5_BOX", 771);
      NUMERIC_5_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_5_BOX_MULTIPLE_OUTLINE", 772);
      NUMERIC_5_BOX_OUTLINE = new IconValue("NUMERIC_5_BOX_OUTLINE", 773);
      NUMERIC_6_BOX = new IconValue("NUMERIC_6_BOX", 774);
      NUMERIC_6_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_6_BOX_MULTIPLE_OUTLINE", 775);
      NUMERIC_6_BOX_OUTLINE = new IconValue("NUMERIC_6_BOX_OUTLINE", 776);
      NUMERIC_7_BOX = new IconValue("NUMERIC_7_BOX", 777);
      NUMERIC_7_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_7_BOX_MULTIPLE_OUTLINE", 778);
      NUMERIC_7_BOX_OUTLINE = new IconValue("NUMERIC_7_BOX_OUTLINE", 779);
      NUMERIC_8_BOX = new IconValue("NUMERIC_8_BOX", 780);
      NUMERIC_8_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_8_BOX_MULTIPLE_OUTLINE", 781);
      NUMERIC_8_BOX_OUTLINE = new IconValue("NUMERIC_8_BOX_OUTLINE", 782);
      NUMERIC_9_BOX = new IconValue("NUMERIC_9_BOX", 783);
      NUMERIC_9_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_9_BOX_MULTIPLE_OUTLINE", 784);
      NUMERIC_9_BOX_OUTLINE = new IconValue("NUMERIC_9_BOX_OUTLINE", 785);
      NUMERIC_9_PLUS_BOX = new IconValue("NUMERIC_9_PLUS_BOX", 786);
      NUMERIC_9_PLUS_BOX_MULTIPLE_OUTLINE = new IconValue("NUMERIC_9_PLUS_BOX_MULTIPLE_OUTLINE", 787);
      NUMERIC_9_PLUS_BOX_OUTLINE = new IconValue("NUMERIC_9_PLUS_BOX_OUTLINE", 788);
      NUTRITON = new IconValue("NUTRITON", 789);
      OFFICE = new IconValue("OFFICE", 790);
      OIL = new IconValue("OIL", 791);
      OMEGA = new IconValue("OMEGA", 792);
      ONEDRIVE = new IconValue("ONEDRIVE", 793);
      OPEN_IN_APP = new IconValue("OPEN_IN_APP", 794);
      OPEN_IN_NEW = new IconValue("OPEN_IN_NEW", 795);
      ORNAMENT = new IconValue("ORNAMENT", 796);
      ORNAMENT_VARIANT = new IconValue("ORNAMENT_VARIANT", 797);
      OUTBOX = new IconValue("OUTBOX", 798);
      PACKAGE = new IconValue("PACKAGE", 799);
      PACKAGE_DOWN = new IconValue("PACKAGE_DOWN", 800);
      PACKAGE_UP = new IconValue("PACKAGE_UP", 801);
      PACKAGE_VARIANT = new IconValue("PACKAGE_VARIANT", 802);
      PACKAGE_VARIANT_CLOSED = new IconValue("PACKAGE_VARIANT_CLOSED", 803);
      PALETTE = new IconValue("PALETTE", 804);
      PALETTE_ADVANCED = new IconValue("PALETTE_ADVANCED", 805);
      PANDA = new IconValue("PANDA", 806);
      PANDORA = new IconValue("PANDORA", 807);
      PANORAMA = new IconValue("PANORAMA", 808);
      PANORAMA_FISHEYE = new IconValue("PANORAMA_FISHEYE", 809);
      PANORAMA_HORIZONTAL = new IconValue("PANORAMA_HORIZONTAL", 810);
      PANORAMA_VERTICAL = new IconValue("PANORAMA_VERTICAL", 811);
      PANORAMA_WIDE_ANGLE = new IconValue("PANORAMA_WIDE_ANGLE", 812);
      PAPER_CUT_VERTICAL = new IconValue("PAPER_CUT_VERTICAL", 813);
      PAPERCLIP = new IconValue("PAPERCLIP", 814);
      PARKING = new IconValue("PARKING", 815);
      PAUSE = new IconValue("PAUSE", 816);
      PAUSE_CIRCLE = new IconValue("PAUSE_CIRCLE", 817);
      PAUSE_CIRCLE_OUTLINE = new IconValue("PAUSE_CIRCLE_OUTLINE", 818);
      PAUSE_OCTAGON = new IconValue("PAUSE_OCTAGON", 819);
      PAUSE_OCTAGON_OUTLINE = new IconValue("PAUSE_OCTAGON_OUTLINE", 820);
      PEN = new IconValue("PEN", 821);
      PENCIL = new IconValue("PENCIL", 822);
      PENCIL_BOX = new IconValue("PENCIL_BOX", 823);
      PENCIL_BOX_OUTLINE = new IconValue("PENCIL_BOX_OUTLINE", 824);
      PHARMACY = new IconValue("PHARMACY", 825);
      PHONE = new IconValue("PHONE", 826);
      PHONE_BLUETOOTH = new IconValue("PHONE_BLUETOOTH", 827);
      PHONE_FORWARD = new IconValue("PHONE_FORWARD", 828);
      PHONE_HANGUP = new IconValue("PHONE_HANGUP", 829);
      PHONE_IN_TALK = new IconValue("PHONE_IN_TALK", 830);
      PHONE_LOCKED = new IconValue("PHONE_LOCKED", 831);
      PHONE_MISSED = new IconValue("PHONE_MISSED", 832);
      PHONE_PAUSED = new IconValue("PHONE_PAUSED", 833);
      PHONE_SETTINGS = new IconValue("PHONE_SETTINGS", 834);
      PIG = new IconValue("PIG", 835);
      PILL = new IconValue("PILL", 836);
      PIN = new IconValue("PIN", 837);
      PIN_OFF = new IconValue("PIN_OFF", 838);
      PINE_TREE = new IconValue("PINE_TREE", 839);
      PINE_TREE_BOX = new IconValue("PINE_TREE_BOX", 840);
      PINTEREST = new IconValue("PINTEREST", 841);
      PINTEREST_BOX = new IconValue("PINTEREST_BOX", 842);
      PIZZA = new IconValue("PIZZA", 843);
      PLAY = new IconValue("PLAY", 844);
      PLAY_BOX_OUTLINE = new IconValue("PLAY_BOX_OUTLINE", 845);
      PLAY_CIRCLE = new IconValue("PLAY_CIRCLE", 846);
      PLAY_CIRCLE_OUTLINE = new IconValue("PLAY_CIRCLE_OUTLINE", 847);
      PLAYLIST_MINUS = new IconValue("PLAYLIST_MINUS", 848);
      PLAYLIST_PLUS = new IconValue("PLAYLIST_PLUS", 849);
      PLAYSTATION = new IconValue("PLAYSTATION", 850);
      PLUS = new IconValue("PLUS", 851);
      PLUS_BOX = new IconValue("PLUS_BOX", 852);
      PLUS_CIRCLE = new IconValue("PLUS_CIRCLE", 853);
      PLUS_CIRCLE_OUTLINE = new IconValue("PLUS_CIRCLE_OUTLINE", 854);
      PLUS_NETWORK = new IconValue("PLUS_NETWORK", 855);
      PLUS_ONE = new IconValue("PLUS_ONE", 856);
      POCKET = new IconValue("POCKET", 857);
      POLL = new IconValue("POLL", 858);
      POLL_BOX = new IconValue("POLL_BOX", 859);
      POLYMER = new IconValue("POLYMER", 860);
      POPCORN = new IconValue("POPCORN", 861);
      POUND = new IconValue("POUND", 862);
      POUND_BOX = new IconValue("POUND_BOX", 863);
      POWER = new IconValue("POWER", 864);
      POWER_SETTINGS = new IconValue("POWER_SETTINGS", 865);
      PRESENTATION = new IconValue("PRESENTATION", 866);
      PRESENTATION_PLAY = new IconValue("PRESENTATION_PLAY", 867);
      PRINTER = new IconValue("PRINTER", 868);
      PRINTER_3D = new IconValue("PRINTER_3D", 869);
      PULSE = new IconValue("PULSE", 870);
      PUZZLE = new IconValue("PUZZLE", 871);
      QRCODE = new IconValue("QRCODE", 872);
      QUADCOPTER = new IconValue("QUADCOPTER", 873);
      QUALITY_HIGH = new IconValue("QUALITY_HIGH", 874);
      QUICKTIME = new IconValue("QUICKTIME", 875);
      RADIATOR = new IconValue("RADIATOR", 876);
      RADIO = new IconValue("RADIO", 877);
      RADIO_TOWER = new IconValue("RADIO_TOWER", 878);
      RADIOACTIVE = new IconValue("RADIOACTIVE", 879);
      RADIOBOX_BLANK = new IconValue("RADIOBOX_BLANK", 880);
      RADIOBOX_MARKED = new IconValue("RADIOBOX_MARKED", 881);
      RASPBERRYPI = new IconValue("RASPBERRYPI", 882);
      RDIO = new IconValue("RDIO", 883);
      READ = new IconValue("READ", 884);
      READABILITY = new IconValue("READABILITY", 885);
      RECEIPT = new IconValue("RECEIPT", 886);
      RECYCLE = new IconValue("RECYCLE", 887);
      REDO = new IconValue("REDO", 888);
      REDO_VARIANT = new IconValue("REDO_VARIANT", 889);
      REFRESH = new IconValue("REFRESH", 890);
      RELATIVE_SCALE = new IconValue("RELATIVE_SCALE", 891);
      RELOAD = new IconValue("RELOAD", 892);
      REMOTE = new IconValue("REMOTE", 893);
      RENAME_BOX = new IconValue("RENAME_BOX", 894);
      REPEAT = new IconValue("REPEAT", 895);
      REPEAT_OFF = new IconValue("REPEAT_OFF", 896);
      REPEAT_ONCE = new IconValue("REPEAT_ONCE", 897);
      REPLAY = new IconValue("REPLAY", 898);
      REPLY = new IconValue("REPLY", 899);
      REPLY_ALL = new IconValue("REPLY_ALL", 900);
      REPRODUCTION = new IconValue("REPRODUCTION", 901);
      RESIZE_BOTTOM_RIGHT = new IconValue("RESIZE_BOTTOM_RIGHT", 902);
      RESPONSIVE = new IconValue("RESPONSIVE", 903);
      REWIND = new IconValue("REWIND", 904);
      RIBBON = new IconValue("RIBBON", 905);
      ROCKET = new IconValue("ROCKET", 906);
      ROTATE_3D = new IconValue("ROTATE_3D", 907);
      ROTATE_LEFT = new IconValue("ROTATE_LEFT", 908);
      ROTATE_LEFT_VARIANT = new IconValue("ROTATE_LEFT_VARIANT", 909);
      ROTATE_RIGHT = new IconValue("ROTATE_RIGHT", 910);
      ROTATE_RIGHT_VARIANT = new IconValue("ROTATE_RIGHT_VARIANT", 911);
      ROUTES = new IconValue("ROUTES", 912);
      RSS = new IconValue("RSS", 913);
      RSS_BOX = new IconValue("RSS_BOX", 914);
      RULER = new IconValue("RULER", 915);
      RUN = new IconValue("RUN", 916);
      SATELLITE = new IconValue("SATELLITE", 917);
      SATELLITE_VARIANT = new IconValue("SATELLITE_VARIANT", 918);
      SCALE = new IconValue("SCALE", 919);
      SCALE_BATHROOM = new IconValue("SCALE_BATHROOM", 920);
      SCHOOL = new IconValue("SCHOOL", 921);
      SCREEN_ROTATION = new IconValue("SCREEN_ROTATION", 922);
      SCREEN_ROTATION_LOCK = new IconValue("SCREEN_ROTATION_LOCK", 923);
      SCRIPT = new IconValue("SCRIPT", 924);
      SD = new IconValue("SD", 925);
      SECURITY = new IconValue("SECURITY", 926);
      SECURITY_NETWORK = new IconValue("SECURITY_NETWORK", 927);
      SELECT = new IconValue("SELECT", 928);
      SELECT_ALL = new IconValue("SELECT_ALL", 929);
      SELECT_INVERSE = new IconValue("SELECT_INVERSE", 930);
      SELECT_OFF = new IconValue("SELECT_OFF", 931);
      SEND = new IconValue("SEND", 932);
      SERVER = new IconValue("SERVER", 933);
      SERVER_MINUS = new IconValue("SERVER_MINUS", 934);
      SERVER_NETWORK = new IconValue("SERVER_NETWORK", 935);
      SERVER_NETWORK_OFF = new IconValue("SERVER_NETWORK_OFF", 936);
      SERVER_OFF = new IconValue("SERVER_OFF", 937);
      SERVER_PLUS = new IconValue("SERVER_PLUS", 938);
      SERVER_REMOVE = new IconValue("SERVER_REMOVE", 939);
      SERVER_SECURITY = new IconValue("SERVER_SECURITY", 940);
      SETTINGS = new IconValue("SETTINGS", 941);
      SETTINGS_BOX = new IconValue("SETTINGS_BOX", 942);
      SHAPE_PLUS = new IconValue("SHAPE_PLUS", 943);
      SHARE = new IconValue("SHARE", 944);
      SHARE_VARIANT = new IconValue("SHARE_VARIANT", 945);
      SHIELD = new IconValue("SHIELD", 946);
      SHIELD_OUTLINE = new IconValue("SHIELD_OUTLINE", 947);
      SHOPPING = new IconValue("SHOPPING", 948);
      SHOPPING_MUSIC = new IconValue("SHOPPING_MUSIC", 949);
      SHUFFLE = new IconValue("SHUFFLE", 950);
      SIGMA = new IconValue("SIGMA", 951);
      SIGN_CAUTION = new IconValue("SIGN_CAUTION", 952);
      SILVERWARE = new IconValue("SILVERWARE", 953);
      SILVERWARE_FORK = new IconValue("SILVERWARE_FORK", 954);
      SILVERWARE_SPOON = new IconValue("SILVERWARE_SPOON", 955);
      SILVERWARE_VARIANT = new IconValue("SILVERWARE_VARIANT", 956);
      SIM_ALERT = new IconValue("SIM_ALERT", 957);
      SKIP_NEXT = new IconValue("SKIP_NEXT", 958);
      SKIP_PREVIOUS = new IconValue("SKIP_PREVIOUS", 959);
      SNAPCHAT = new IconValue("SNAPCHAT", 960);
      SNOWMAN = new IconValue("SNOWMAN", 961);
      SORT = new IconValue("SORT", 962);
      SORT_ALPHABETICAL = new IconValue("SORT_ALPHABETICAL", 963);
      SORT_ASCENDING = new IconValue("SORT_ASCENDING", 964);
      SORT_DESCENDING = new IconValue("SORT_DESCENDING", 965);
      SORT_NUMERIC = new IconValue("SORT_NUMERIC", 966);
      SORT_VARIANT = new IconValue("SORT_VARIANT", 967);
      SOUNDCLOUD = new IconValue("SOUNDCLOUD", 968);
      SOURCE_FORK = new IconValue("SOURCE_FORK", 969);
      SOURCE_PULL = new IconValue("SOURCE_PULL", 970);
      SPEAKER = new IconValue("SPEAKER", 971);
      SPEAKER_OFF = new IconValue("SPEAKER_OFF", 972);
      SPEEDOMETER = new IconValue("SPEEDOMETER", 973);
      SPELLCHECK = new IconValue("SPELLCHECK", 974);
      SPOTIFY = new IconValue("SPOTIFY", 975);
      SPOTLIGHT = new IconValue("SPOTLIGHT", 976);
      SPOTLIGHT_BEAM = new IconValue("SPOTLIGHT_BEAM", 977);
      STACKOVERFLOW = new IconValue("STACKOVERFLOW", 978);
      STAR = new IconValue("STAR", 979);
      STAR_CIRCLE = new IconValue("STAR_CIRCLE", 980);
      STAR_HALF = new IconValue("STAR_HALF", 981);
      STAR_OUTLINE = new IconValue("STAR_OUTLINE", 982);
      STOCKING = new IconValue("STOCKING", 983);
      STOP = new IconValue("STOP", 984);
      STORE = new IconValue("STORE", 985);
      STORE_24_HOUR = new IconValue("STORE_24_HOUR", 986);
      STOVE = new IconValue("STOVE", 987);
      SUBWAY = new IconValue("SUBWAY", 988);
      SWAP_HORIZONTAL = new IconValue("SWAP_HORIZONTAL", 989);
      SWAP_VERTICAL = new IconValue("SWAP_VERTICAL", 990);
      SWIM = new IconValue("SWIM", 991);
      SWORD = new IconValue("SWORD", 992);
      SYNC = new IconValue("SYNC", 993);
      SYNC_ALERT = new IconValue("SYNC_ALERT", 994);
      SYNC_OFF = new IconValue("SYNC_OFF", 995);
      TAB = new IconValue("TAB", 996);
      TAB_UNSELECTED = new IconValue("TAB_UNSELECTED", 997);
      TABLE = new IconValue("TABLE", 998);
      TABLE_COLUMN_PLUS_AFTER = new IconValue("TABLE_COLUMN_PLUS_AFTER", 999);
      TABLE_COLUMN_PLUS_BEFORE = new IconValue("TABLE_COLUMN_PLUS_BEFORE", 1000);
      TABLE_COLUMN_REMOVE = new IconValue("TABLE_COLUMN_REMOVE", 1001);
      TABLE_COLUMN_WIDTH = new IconValue("TABLE_COLUMN_WIDTH", 1002);
      TABLE_EDIT = new IconValue("TABLE_EDIT", 1003);
      TABLE_LARGE = new IconValue("TABLE_LARGE", 1004);
      TABLE_ROW_HEIGHT = new IconValue("TABLE_ROW_HEIGHT", 1005);
      TABLE_ROW_PLUS_AFTER = new IconValue("TABLE_ROW_PLUS_AFTER", 1006);
      TABLE_ROW_PLUS_BEFORE = new IconValue("TABLE_ROW_PLUS_BEFORE", 1007);
      TABLE_ROW_REMOVE = new IconValue("TABLE_ROW_REMOVE", 1008);
      TABLET = new IconValue("TABLET", 1009);
      TABLET_ANDROID = new IconValue("TABLET_ANDROID", 1010);
      TABLET_IPAD = new IconValue("TABLET_IPAD", 1011);
      TAG = new IconValue("TAG", 1012);
      TAG_FACES = new IconValue("TAG_FACES", 1013);
      TAG_MULTIPLE = new IconValue("TAG_MULTIPLE", 1014);
      TAG_OUTLINE = new IconValue("TAG_OUTLINE", 1015);
      TAG_TEXT_OUTLINE = new IconValue("TAG_TEXT_OUTLINE", 1016);
      TAXI = new IconValue("TAXI", 1017);
      TELEVISION = new IconValue("TELEVISION", 1018);
      TELEVISION_GUIDE = new IconValue("TELEVISION_GUIDE", 1019);
      TEMPERATURE_CELSIUS = new IconValue("TEMPERATURE_CELSIUS", 1020);
      TEMPERATURE_FAHRENHEIT = new IconValue("TEMPERATURE_FAHRENHEIT", 1021);
      TEMPERATURE_KELVIN = new IconValue("TEMPERATURE_KELVIN", 1022);
      TENT = new IconValue("TENT", 1023);
      TERRAIN = new IconValue("TERRAIN", 1024);
      TEXT_TO_SPEECH = new IconValue("TEXT_TO_SPEECH", 1025);
      TEXT_TO_SPEECH_OFF = new IconValue("TEXT_TO_SPEECH_OFF", 1026);
      TEXTURE = new IconValue("TEXTURE", 1027);
      THEATER = new IconValue("THEATER", 1028);
      THEME_LIGHT_DARK = new IconValue("THEME_LIGHT_DARK", 1029);
      THERMOMETER = new IconValue("THERMOMETER", 1030);
      THERMOMETER_LINES = new IconValue("THERMOMETER_LINES", 1031);
      THUMB_DOWN = new IconValue("THUMB_DOWN", 1032);
      THUMB_DOWN_OUTLINE = new IconValue("THUMB_DOWN_OUTLINE", 1033);
      THUMB_UP = new IconValue("THUMB_UP", 1034);
      THUMB_UP_OUTLINE = new IconValue("THUMB_UP_OUTLINE", 1035);
      THUMBS_UP_DOWN = new IconValue("THUMBS_UP_DOWN", 1036);
      TICKET = new IconValue("TICKET", 1037);
      TICKET_ACCOUNT = new IconValue("TICKET_ACCOUNT", 1038);
      TIE = new IconValue("TIE", 1039);
      TIMELAPSE = new IconValue("TIMELAPSE", 1040);
      TIMER = new IconValue("TIMER", 1041);
      TIMER_10 = new IconValue("TIMER_10", 1042);
      TIMER_3 = new IconValue("TIMER_3", 1043);
      TIMER_OFF = new IconValue("TIMER_OFF", 1044);
      TIMER_SAND = new IconValue("TIMER_SAND", 1045);
      TIMETABLE = new IconValue("TIMETABLE", 1046);
      TOGGLE_SWITCH = new IconValue("TOGGLE_SWITCH", 1047);
      TOGGLE_SWITCH_OFF = new IconValue("TOGGLE_SWITCH_OFF", 1048);
      TOOLTIP = new IconValue("TOOLTIP", 1049);
      TOOLTIP_EDIT = new IconValue("TOOLTIP_EDIT", 1050);
      TOOLTIP_IMAGE = new IconValue("TOOLTIP_IMAGE", 1051);
      TOOLTIP_OUTLINE = new IconValue("TOOLTIP_OUTLINE", 1052);
      TOOLTIP_OUTLINE_PLUS = new IconValue("TOOLTIP_OUTLINE_PLUS", 1053);
      TOOLTIP_TEXT = new IconValue("TOOLTIP_TEXT", 1054);
      TOR = new IconValue("TOR", 1055);
      TRAFFIC_LIGHT = new IconValue("TRAFFIC_LIGHT", 1056);
      TRAIN = new IconValue("TRAIN", 1057);
      TRAM = new IconValue("TRAM", 1058);
      TRANSCRIBE = new IconValue("TRANSCRIBE", 1059);
      TRANSCRIBE_CLOSE = new IconValue("TRANSCRIBE_CLOSE", 1060);
      TRANSFER = new IconValue("TRANSFER", 1061);
      TREE = new IconValue("TREE", 1062);
      TRELLO = new IconValue("TRELLO", 1063);
      TRENDING_DOWN = new IconValue("TRENDING_DOWN", 1064);
      TRENDING_NEUTRAL = new IconValue("TRENDING_NEUTRAL", 1065);
      TRENDING_UP = new IconValue("TRENDING_UP", 1066);
      TROPHY = new IconValue("TROPHY", 1067);
      TROPHY_AWARD = new IconValue("TROPHY_AWARD", 1068);
      TROPHY_VARIANT = new IconValue("TROPHY_VARIANT", 1069);
      TRUCK = new IconValue("TRUCK", 1070);
      TSHIRT_CREW = new IconValue("TSHIRT_CREW", 1071);
      TSHIRT_V = new IconValue("TSHIRT_V", 1072);
      TUMBLR = new IconValue("TUMBLR", 1073);
      TUMBLR_REBLOG = new IconValue("TUMBLR_REBLOG", 1074);
      TWITCH = new IconValue("TWITCH", 1075);
      TWITTER = new IconValue("TWITTER", 1076);
      TWITTER_BOX = new IconValue("TWITTER_BOX", 1077);
      TWITTER_RETWEET = new IconValue("TWITTER_RETWEET", 1078);
      UBUNTU = new IconValue("UBUNTU", 1079);
      UNDO = new IconValue("UNDO", 1080);
      UNDO_VARIANT = new IconValue("UNDO_VARIANT", 1081);
      UNFOLD_LESS = new IconValue("UNFOLD_LESS", 1082);
      UNFOLD_MORE = new IconValue("UNFOLD_MORE", 1083);
      UNTAPPD = new IconValue("UNTAPPD", 1084);
      UPLOAD = new IconValue("UPLOAD", 1085);
      USB = new IconValue("USB", 1086);
      VECTOR_CURVE = new IconValue("VECTOR_CURVE", 1087);
      VECTOR_POINT = new IconValue("VECTOR_POINT", 1088);
      VECTOR_SQUARE = new IconValue("VECTOR_SQUARE", 1089);
      VERIFIED = new IconValue("VERIFIED", 1090);
      VIBRATE = new IconValue("VIBRATE", 1091);
      VIDEO = new IconValue("VIDEO", 1092);
      VIDEO_OFF = new IconValue("VIDEO_OFF", 1093);
      VIDEO_SWITCH = new IconValue("VIDEO_SWITCH", 1094);
      VIEW_AGENDA = new IconValue("VIEW_AGENDA", 1095);
      VIEW_ARRAY = new IconValue("VIEW_ARRAY", 1096);
      VIEW_CAROUSEL = new IconValue("VIEW_CAROUSEL", 1097);
      VIEW_COLUMN = new IconValue("VIEW_COLUMN", 1098);
      VIEW_DASHBOARD = new IconValue("VIEW_DASHBOARD", 1099);
      VIEW_DAY = new IconValue("VIEW_DAY", 1100);
      VIEW_HEADLINE = new IconValue("VIEW_HEADLINE", 1101);
      VIEW_LIST = new IconValue("VIEW_LIST", 1102);
      VIEW_MODULE = new IconValue("VIEW_MODULE", 1103);
      VIEW_QUILT = new IconValue("VIEW_QUILT", 1104);
      VIEW_STREAM = new IconValue("VIEW_STREAM", 1105);
      VIEW_WEEK = new IconValue("VIEW_WEEK", 1106);
      VIMEO = new IconValue("VIMEO", 1107);
      VK = new IconValue("VK", 1108);
      VOICEMAIL = new IconValue("VOICEMAIL", 1109);
      VOLUME_HIGH = new IconValue("VOLUME_HIGH", 1110);
      VOLUME_LOW = new IconValue("VOLUME_LOW", 1111);
      VOLUME_MEDIUM = new IconValue("VOLUME_MEDIUM", 1112);
      VOLUME_OFF = new IconValue("VOLUME_OFF", 1113);
      WALK = new IconValue("WALK", 1114);
      WALLET = new IconValue("WALLET", 1115);
      WALLET_GIFTCARD = new IconValue("WALLET_GIFTCARD", 1116);
      WALLET_MEMBERSHIP = new IconValue("WALLET_MEMBERSHIP", 1117);
      WALLET_TRAVEL = new IconValue("WALLET_TRAVEL", 1118);
      WATCH = new IconValue("WATCH", 1119);
      WATCH_EXPORT = new IconValue("WATCH_EXPORT", 1120);
      WATCH_IMPORT = new IconValue("WATCH_IMPORT", 1121);
      WATER = new IconValue("WATER", 1122);
      WATER_OFF = new IconValue("WATER_OFF", 1123);
      WATER_PUMP = new IconValue("WATER_PUMP", 1124);
      WEATHER_CLOUDY = new IconValue("WEATHER_CLOUDY", 1125);
      WEATHER_HAIL = new IconValue("WEATHER_HAIL", 1126);
      WEATHER_LIGHTNING = new IconValue("WEATHER_LIGHTNING", 1127);
      WEATHER_NIGHT = new IconValue("WEATHER_NIGHT", 1128);
      WEATHER_PARTLYCLOUDY = new IconValue("WEATHER_PARTLYCLOUDY", 1129);
      WEATHER_POURING = new IconValue("WEATHER_POURING", 1130);
      WEATHER_RAINY = new IconValue("WEATHER_RAINY", 1131);
      WEATHER_SNOWY = new IconValue("WEATHER_SNOWY", 1132);
      WEATHER_SUNNY = new IconValue("WEATHER_SUNNY", 1133);
      WEATHER_SUNSET = new IconValue("WEATHER_SUNSET", 1134);
      WEATHER_SUNSET_DOWN = new IconValue("WEATHER_SUNSET_DOWN", 1135);
      WEATHER_SUNSET_UP = new IconValue("WEATHER_SUNSET_UP", 1136);
      WEATHER_WINDY = new IconValue("WEATHER_WINDY", 1137);
      WEATHER_WINDY_VARIANT = new IconValue("WEATHER_WINDY_VARIANT", 1138);
      WEB = new IconValue("WEB", 1139);
      WEBCAM = new IconValue("WEBCAM", 1140);
      WEIGHT = new IconValue("WEIGHT", 1141);
      WEIGHT_KILOGRAM = new IconValue("WEIGHT_KILOGRAM", 1142);
      WHATSAPP = new IconValue("WHATSAPP", 1143);
      WHEELCHAIR_ACCESSIBILITY = new IconValue("WHEELCHAIR_ACCESSIBILITY", 1144);
      WHITE_BALANCE_AUTO = new IconValue("WHITE_BALANCE_AUTO", 1145);
      WHITE_BALANCE_INCANDESCENT = new IconValue("WHITE_BALANCE_INCANDESCENT", 1146);
      WHITE_BALANCE_IRRADESCENT = new IconValue("WHITE_BALANCE_IRRADESCENT", 1147);
      WHITE_BALANCE_SUNNY = new IconValue("WHITE_BALANCE_SUNNY", 1148);
      WIFI = new IconValue("WIFI", 1149);
      WII = new IconValue("WII", 1150);
      WIKIPEDIA = new IconValue("WIKIPEDIA", 1151);
      WINDOW_CLOSE = new IconValue("WINDOW_CLOSE", 1152);
      WINDOW_CLOSED = new IconValue("WINDOW_CLOSED", 1153);
      WINDOW_MAXIMIZE = new IconValue("WINDOW_MAXIMIZE", 1154);
      WINDOW_MINIMIZE = new IconValue("WINDOW_MINIMIZE", 1155);
      WINDOW_OPEN = new IconValue("WINDOW_OPEN", 1156);
      WINDOW_RESTORE = new IconValue("WINDOW_RESTORE", 1157);
      WINDOWS = new IconValue("WINDOWS", 1158);
      WORDPRESS = new IconValue("WORDPRESS", 1159);
      WORKER = new IconValue("WORKER", 1160);
      WUNDERLIST = new IconValue("WUNDERLIST", 1161);
      XBOX = new IconValue("XBOX", 1162);
      XBOX_CONTROLLER = new IconValue("XBOX_CONTROLLER", 1163);
      XBOX_CONTROLLER_OFF = new IconValue("XBOX_CONTROLLER_OFF", 1164);
      XDA = new IconValue("XDA", 1165);
      XML = new IconValue("XML", 1166);
      YEAST = new IconValue("YEAST", 1167);
      YOUTUBE_PLAY = new IconValue("YOUTUBE_PLAY", 1168);
      ZIP_BOX = new IconValue("ZIP_BOX", 1169);
      $VALUES = new IconValue[] { 
          ACCOUNT, ACCOUNT_ALERT, ACCOUNT_BOX, ACCOUNT_BOX_OUTLINE, ACCOUNT_CHECK, ACCOUNT_CIRCLE, ACCOUNT_KEY, ACCOUNT_LOCATION, ACCOUNT_MINUS, ACCOUNT_MULTIPLE, 
          ACCOUNT_MULTIPLE_OUTLINE, ACCOUNT_MULTIPLE_PLUS, ACCOUNT_NETWORK, ACCOUNT_OUTLINE, ACCOUNT_PLUS, ACCOUNT_REMOVE, ACCOUNT_SEARCH, ACCOUNT_STAR, ACCOUNT_STAR_VARIANT, ACCOUNT_SWITCH, 
          AIRBALLOON, AIRPLANE, AIRPLANE_OFF, ALARM, ALARM_CHECK, ALARM_MULTIPLE, ALARM_OFF, ALARM_PLUS, ALBUM, ALERT, 
          ALERT_BOX, ALERT_CIRCLE, ALERT_OCTAGON, ALPHA, ALPHABETICAL, AMAZON, AMAZON_CLOUDDRIVE, AMBULANCE, ANDROID, ANDROID_DEBUG_BRIDGE, 
          ANDROID_STUDIO, APPLE, APPLE_FINDER, APPLE_MOBILEME, APPLE_SAFARI, APPNET, APPS, ARCHIVE, ARRANGE_BRING_FORWARD, ARRANGE_BRING_TO_FRONT, 
          ARRANGE_SEND_BACKWARD, ARRANGE_SEND_TO_BACK, ARROW_ALL, ARROW_BOTTOM_LEFT, ARROW_BOTTOM_RIGHT, ARROW_COLLAPSE, ARROW_DOWN, ARROW_DOWN_BOLD, ARROW_DOWN_BOLD_CIRCLE, ARROW_DOWN_BOLD_CIRCLE_OUTLINE, 
          ARROW_DOWN_BOLD_HEXAGON_OUTLINE, ARROW_EXPAND, ARROW_LEFT, ARROW_LEFT_BOLD, ARROW_LEFT_BOLD_CIRCLE, ARROW_LEFT_BOLD_CIRCLE_OUTLINE, ARROW_LEFT_BOLD_HEXAGON_OUTLINE, ARROW_RIGHT, ARROW_RIGHT_BOLD, ARROW_RIGHT_BOLD_CIRCLE, 
          ARROW_RIGHT_BOLD_CIRCLE_OUTLINE, ARROW_RIGHT_BOLD_HEXAGON_OUTLINE, ARROW_TOP_LEFT, ARROW_TOP_RIGHT, ARROW_UP, ARROW_UP_BOLD, ARROW_UP_BOLD_CIRCLE, ARROW_UP_BOLD_CIRCLE_OUTLINE, ARROW_UP_BOLD_HEXAGON_OUTLINE, AT, 
          ATTACHMENT, AUDIOBOOK, AUTO_FIX, AUTO_UPLOAD, BACKBURGER, BACKUP_RESTORE, BANK, BARCODE, BARLEY, BARREL, 
          BASECAMP, BASKET, BASKET_FILL, BASKET_UNFILL, BATTERY, BATTERY_20, BATTERY_30, BATTERY_40, BATTERY_60, BATTERY_80, 
          BATTERY_90, BATTERY_ALERT, BATTERY_CHARGING_100, BATTERY_CHARGING_20, BATTERY_CHARGING_30, BATTERY_CHARGING_40, BATTERY_CHARGING_60, BATTERY_CHARGING_80, BATTERY_CHARGING_90, BATTERY_MINUS, 
          BATTERY_NEGATIVE, BATTERY_OUTLINE, BATTERY_PLUS, BATTERY_POSITIVE, BATTERY_UNKNOWN, BEACH, BEAKER, BEAKER_EMPTY, BEAKER_EMPTY_OUTLINE, BEAKER_OUTLINE, 
          BEATS, BEER, BEHANCE, BELL, BELL_OFF, BELL_OUTLINE, BELL_RING, BELL_RING_OUTLINE, BELL_SLEEP, BETA, 
          BIKE, BING, BINOCULARS, BIO, BIOHAZARD, BLACK_MESA, BLACKBERRY, BLINDS, BLOCK_HELPER, BLOGGER, 
          BLUETOOTH, BLUETOOTH_AUDIO, BLUETOOTH_CONNECT, BLUETOOTH_SETTINGS, BLUR, BLUR_LINEAR, BLUR_OFF, BLUR_RADIAL, BONE, BOOK, 
          BOOK_MULTIPLE, BOOK_MULTIPLE_VARIANT, BOOK_OPEN, BOOK_VARIANT, BOOKMARK, BOOKMARK_CHECK, BOOKMARK_MUSIC, BOOKMARK_OUTLINE, BOOKMARK_OUTLINE_PLUS, BOOKMARK_PLUS, 
          BOOKMARK_REMOVE, BORDER_ALL, BORDER_BOTTOM, BORDER_COLOR, BORDER_HORIZONTAL, BORDER_INSIDE, BORDER_LEFT, BORDER_NONE, BORDER_OUTSIDE, BORDER_RIGHT, 
          BORDER_TOP, BORDER_VERTICAL, BOWLING, BOX, BRIEFCASE, BRIEFCASE_CHECK, BRIEFCASE_DOWNLOAD, BRIEFCASE_UPLOAD, BRIGHTNESS_1, BRIGHTNESS_2, 
          BRIGHTNESS_3, BRIGHTNESS_4, BRIGHTNESS_5, BRIGHTNESS_6, BRIGHTNESS_7, BRIGHTNESS_AUTO, BROOM, BRUSH, BUG, BULLHORN, 
          BUS, CAKE, CAKE_VARIANT, CALCULATOR, CALENDAR, CALENDAR_BLANK, CALENDAR_CHECK, CALENDAR_CLOCK, CALENDAR_MULTIPLE, CALENDAR_MULTIPLE_CHECK, 
          CALENDAR_PLUS, CALENDAR_REMOVE, CALENDAR_TEXT, CALENDAR_TODAY, CAMCORDER, CAMCORDER_BOX, CAMCORDER_BOX_OFF, CAMCORDER_OFF, CAMERA, CAMERA_IRIS, 
          CAMERA_PARTY_MODE, CAMERA_SWITCH, CAMERA_TIMER, CANDYCANE, CAR, CAR_WASH, CARROT, CART, CART_OUTLINE, CASH, 
          CASH_MULTIPLE, CASH_USD, CAST, CAST_CONNECTED, CASTLE, CAT, CELLPHONE, CELLPHONE_ANDROID, CELLPHONE_DOCK, CELLPHONE_IPHONE, 
          CELLPHONE_LINK, CELLPHONE_LINK_OFF, CELLPHONE_SETTINGS, CHAIR_SCHOOL, CHART_ARC, CHART_AREASPLINE, CHART_BAR, CHART_HISTOGRAM, CHART_LINE, CHART_PIE, 
          CHECK, CHECK_ALL, CHECKBOX_BLANK, CHECKBOX_BLANK_CIRCLE, CHECKBOX_BLANK_CIRCLE_OUTLINE, CHECKBOX_BLANK_OUTLINE, CHECKBOX_MARKED, CHECKBOX_MARKED_CIRCLE, CHECKBOX_MARKED_CIRCLE_OUTLINE, CHECKBOX_MARKED_OUTLINE, 
          CHECKBOX_MULTIPLE_BLANK, CHECKBOX_MULTIPLE_BLANK_OUTLINE, CHECKBOX_MULTIPLE_MARKED, CHECKBOX_MULTIPLE_MARKED_OUTLINE, CHECKERBOARD, CHEVRON_DOUBLE_DOWN, CHEVRON_DOUBLE_LEFT, CHEVRON_DOUBLE_RIGHT, CHEVRON_DOUBLE_UP, CHEVRON_DOWN, 
          CHEVRON_LEFT, CHEVRON_RIGHT, CHEVRON_UP, CHURCH, CISCO_WEBEX, CITY, CLIPBOARD, CLIPBOARD_ACCOUNT, CLIPBOARD_ALERT, CLIPBOARD_ARROW_DOWN, 
          CLIPBOARD_ARROW_LEFT, CLIPBOARD_CHECK, CLIPBOARD_OUTLINE, CLIPBOARD_TEXT, CLIPPY, CLOCK, CLOCK_FAST, CLOSE, CLOSE_BOX, CLOSE_BOX_OUTLINE, 
          CLOSE_CIRCLE, CLOSE_CIRCLE_OUTLINE, CLOSE_NETWORK, CLOSED_CAPTION, CLOUD, CLOUD_CHECK, CLOUD_CIRCLE, CLOUD_DOWNLOAD, CLOUD_OUTLINE, CLOUD_OUTLINE_OFF, 
          CLOUD_UPLOAD, CODE_ARRAY, CODE_STRING, CODEPEN, COFFEE, COFFEE_TO_GO, COIN, COLOR_HELPER, COMMENT, COMMENT_ACCOUNT, 
          COMMENT_ACCOUNT_OUTLINE, COMMENT_ALERT, COMMENT_ALERT_OUTLINE, COMMENT_CHECK, COMMENT_CHECK_OUTLINE, COMMENT_MULTIPLE_OUTLINE, COMMENT_OUTLINE, COMMENT_PLUS_OUTLINE, COMMENT_PROCESSING, COMMENT_PROCESSING_OUTLINE, 
          COMMENT_REMOVE_OUTLINE, COMMENT_TEXT, COMMENT_TEXT_OUTLINE, COMPARE, COMPASS, COMPASS_OUTLINE, CONSOLE, CONTENT_COPY, CONTENT_CUT, CONTENT_PASTE, 
          CONTENT_SAVE, CONTENT_SAVE_ALL, CONTRAST, CONTRAST_BOX, CONTRAST_CIRCLE, COW, CREDIT_CARD, CREDIT_CARD_MULTIPLE, CROP, CROP_FREE, 
          CROP_LANDSCAPE, CROP_PORTRAIT, CROP_SQUARE, CROSSHAIRS, CROSSHAIRS_GPS, CROWN, CUBE, CUBE_OUTLINE, CUBE_UNFOLDED, CUP, 
          CUP_WATER, CURRENCY_BTC, CURRENCY_EUR, CURRENCY_GBP, CURRENCY_INR, CURRENCY_RUB, CURRENCY_TRY, CURRENCY_USD, CURSOR_DEFAULT, CURSOR_DEFAULT_OUTLINE, 
          CURSOR_MOVE, CURSOR_POINTER, DATABASE, DATABASE_MINUS, DATABASE_OUTLINE, DATABASE_PLUS, DEBUG_STEP_INTO, DEBUG_STEP_OUT, DEBUG_STEP_OVER, DELETE, 
          DELETE_VARIANT, DESKPHONE, DESKTOP_MAC, DESKTOP_TOWER, DETAILS, DEVIANTART, DICE, DICE_1, DICE_2, DICE_3, 
          DICE_4, DICE_5, DICE_6, DIRECTIONS, DISK_ALERT, DISQUS, DISQUS_OUTLINE, DIVISION, DIVISION_BOX, DNS, 
          DOMAIN, DOTS_HORIZONTAL, DOTS_VERTICAL, DOWNLOAD, DRAG, DRAG_HORIZONTAL, DRAG_VERTICAL, DRAWING, DRAWING_BOX, DRIBBBLE, 
          DRIBBBLE_BOX, DRONE, DROPBOX, DUCK, DUMBBELL, EARTH, EARTH_OFF, EDGE, ELEVATION_DECLINE, ELEVATION_RISE, 
          ELEVATOR, EMAIL, EMAIL_OPEN, EMAIL_OUTLINE, EMOTICON, EMOTICON_COOL, EMOTICON_DEVIL, EMOTICON_HAPPY, EMOTICON_NEUTRAL, EMOTICON_POOP, 
          EMOTICON_SAD, EMOTICON_TONGUE, EQUAL, EQUAL_BOX, ERASER, ESCALATOR, ETSY, EVERNOTE, EXCLAMATION, EXIT_TO_APP, 
          EXPORT, EYE, EYE_OFF, EYEDROPPER, EYEDROPPER_VARIANT, FACEBOOK, FACEBOOK_BOX, FACEBOOK_MESSENGER, FACTORY, FAN, 
          FAST_FORWARD, FERRY, FILE, FILE_CLOUD, FILE_DELIMITED, FILE_DOCUMENT, FILE_DOCUMENT_BOX, FILE_EXCEL, FILE_EXCEL_BOX, FILE_FIND, 
          FILE_IMAGE, FILE_IMAGE_BOX, FILE_MUSIC, FILE_OUTLINE, FILE_PDF, FILE_PDF_BOX, FILE_POWERPOINT, FILE_POWERPOINT_BOX, FILE_PRESENTATION_BOX, FILE_VIDEO, 
          FILE_WORD, FILE_WORD_BOX, FILE_XML, FILM, FILMSTRIP, FILMSTRIP_OFF, FILTER, FILTER_OUTLINE, FILTER_REMOVE, FILTER_REMOVE_OUTLINE, 
          FILTER_VARIANT, FIRE, FIREFOX, FISH, FLAG, FLAG_CHECKERED, FLAG_OUTLINE, FLAG_OUTLINE_VARIANT, FLAG_TRIANGLE, FLAG_VARIANT, 
          FLASH, FLASH_AUTO, FLASH_OFF, FLASHLIGHT, FLASHLIGHT_OFF, FLATTR, FLIP_TO_BACK, FLIP_TO_FRONT, FLOPPY, FLOWER, 
          FOLDER, FOLDER_ACCOUNT, FOLDER_DOWNLOAD, FOLDER_GOOGLE_DRIVE, FOLDER_IMAGE, FOLDER_LOCK, FOLDER_LOCK_OPEN, FOLDER_MOVE, FOLDER_MULTIPLE, FOLDER_MULTIPLE_IMAGE, 
          FOLDER_MULTIPLE_OUTLINE, FOLDER_OUTLINE, FOLDER_PLUS, FOLDER_REMOVE, FOLDER_UPLOAD, FOOD, FOOD_APPLE, FOOD_VARIANT, FOOTBALL, FOOTBALL_HELMET, 
          FORMAT_ALIGN_CENTER, FORMAT_ALIGN_JUSTIFY, FORMAT_ALIGN_LEFT, FORMAT_ALIGN_RIGHT, FORMAT_BOLD, FORMAT_CLEAR, FORMAT_COLOR_FILL, FORMAT_HEADER_1, FORMAT_HEADER_2, FORMAT_HEADER_3, 
          FORMAT_HEADER_4, FORMAT_HEADER_5, FORMAT_HEADER_6, FORMAT_HEADER_POUND, FORMAT_INDENT_DECREASE, FORMAT_INDENT_INCREASE, FORMAT_ITALIC, FORMAT_LINE_SPACING, FORMAT_LIST_BULLETED, FORMAT_LIST_NUMBERS, 
          FORMAT_PAINT, FORMAT_PARAGRAPH, FORMAT_QUOTE, FORMAT_SIZE, FORMAT_STRIKETHROUGH, FORMAT_SUBSCRIPT, FORMAT_SUPERSCRIPT, FORMAT_TEXT, FORMAT_TEXTDIRECTION_L_TO_R, FORMAT_TEXTDIRECTION_R_TO_L, 
          FORMAT_UNDERLINE, FORUM, FORWARD, FOURSQUARE, FRIDGE, FULLSCREEN, FULLSCREEN_EXIT, FUNCTION, GAMEPAD, GAMEPAD_VARIANT, 
          GAS_STATION, GAVEL, GENDER_FEMALE, GENDER_MALE, GENDER_MALE_FEMALE, GENDER_TRANSGENDER, GIFT, GITHUB_BOX, GITHUB_CIRCLE, GLASS_FLUTE, 
          GLASS_MUG, GLASS_STANGE, GLASS_TULIP, GMAIL, GOOGLE, GOOGLE_CHROME, GOOGLE_CIRCLES, GOOGLE_CIRCLES_COMMUNITIES, GOOGLE_CIRCLES_EXTENDED, GOOGLE_CIRCLES_GROUP, 
          GOOGLE_CONTROLLER, GOOGLE_CONTROLLER_OFF, GOOGLE_DRIVE, GOOGLE_EARTH, GOOGLE_GLASS, GOOGLE_MAPS, GOOGLE_PAGES, GOOGLE_PLAY, GOOGLE_PLUS, GOOGLE_PLUS_BOX, 
          GRID, GRID_OFF, GUITAR_PICK, GUITAR_PICK_OUTLINE, HAND_POINTING_RIGHT, HANGER, HANGOUTS, HARDDISK, HEADPHONES, HEADPHONES_BOX, 
          HEADPHONES_SETTINGS, HEADSET, HEADSET_DOCK, HEADSET_OFF, HEART, HEART_BOX, HEART_BOX_OUTLINE, HEART_BROKEN, HEART_OUTLINE, HELP, 
          HELP_CIRCLE, HEXAGON, HEXAGON_OUTLINE, HISTORY, HOLOLENS, HOME, HOME_MODERN, HOME_VARIANT, HOPS, HOSPITAL, 
          HOSPITAL_BUILDING, HOSPITAL_MARKER, HOTEL, HOUZZ, HOUZZ_BOX, HUMAN, HUMAN_CHILD, HUMAN_MALE_FEMALE, IMAGE_ALBUM, IMAGE_AREA, 
          IMAGE_AREA_CLOSE, IMAGE_BROKEN, IMAGE_FILTER, IMAGE_FILTER_BLACK_WHITE, IMAGE_FILTER_CENTER_FOCUS, IMAGE_FILTER_DRAMA, IMAGE_FILTER_FRAMES, IMAGE_FILTER_HDR, IMAGE_FILTER_NONE, IMAGE_FILTER_TILT_SHIFT, 
          IMAGE_FILTER_VINTAGE, IMPORT, INBOX, INFORMATION, INFORMATION_OUTLINE, INSTAGRAM, INSTAPAPER, INTERNET_EXPLORER, INVERT_COLORS, JIRA, 
          KEG, KEY, KEY_CHANGE, KEY_MINUS, KEY_PLUS, KEY_REMOVE, KEY_VARIANT, KEYBOARD, KEYBOARD_BACKSPACE, KEYBOARD_CAPS, 
          KEYBOARD_CLOSE, KEYBOARD_OFF, KEYBOARD_RETURN, KEYBOARD_TAB, KEYBOARD_VARIANT, LABEL, LABEL_OUTLINE, LANGUAGE_CSHARP, LANGUAGE_CSS3, LANGUAGE_HTML5, 
          LANGUAGE_JAVASCRIPT, LANGUAGE_PYTHON, LANGUAGE_PYTHON_TEXT, LAPTOP, LAPTOP_CHROMEBOOK, LAPTOP_MAC, LAPTOP_WINDOWS, LASTFM, LAUNCH, LAYERS, 
          LAYERS_OFF, LEAF, LIBRARY, LIBRARY_BOOKS, LIBRARY_MUSIC, LIBRARY_PLUS, LIGHTBULB, LIGHTBULB_OUTLINE, LINK, LINK_VARIANT, 
          LINKEDIN, LINKEDIN_BOX, LINUX, LOCK, LOCK_OPEN, LOCK_OPEN_OUTLINE, LOCK_OUTLINE, LOGIN, LOGOUT, LOOKS, 
          LOUPE, LUMX, MAGNIFY, MAGNIFY_MINUS, MAGNIFY_PLUS, MAP, MAP_MARKER, MAP_MARKER_CIRCLE, MAP_MARKER_MULTIPLE, MAP_MARKER_OFF, 
          MAP_MARKER_RADIUS, MARGIN, MARKDOWN, MARKER_CHECK, MARTINI, MATERIAL_UI, MATH_COMPASS, MAXCDN, MEMORY, MENU, 
          MENU_DOWN, MENU_LEFT, MENU_RIGHT, MENU_UP, MESSAGE, MESSAGE_ALERT, MESSAGE_DRAW, MESSAGE_IMAGE, MESSAGE_PROCESSING, MESSAGE_REPLY, 
          MESSAGE_TEXT, MESSAGE_TEXT_OUTLINE, MESSAGE_VIDEO, MICROPHONE, MICROPHONE_OFF, MICROPHONE_OUTLINE, MICROPHONE_SETTINGS, MICROPHONE_VARIANT, MICROPHONE_VARIANT_OFF, MINUS, 
          MINUS_BOX, MINUS_CIRCLE, MINUS_CIRCLE_OUTLINE, MINUS_NETWORK, MONITOR, MONITOR_MULTIPLE, MORE, MOTORBIKE, MOUSE, MOUSE_OFF, 
          MOUSE_VARIANT, MOUSE_VARIANT_OFF, MOVIE, MULTIPLICATION, MULTIPLICATION_BOX, MUSIC_BOX, MUSIC_BOX_OUTLINE, MUSIC_CIRCLE, MUSIC_NOTE, MUSIC_NOTE_EIGHTH, 
          MUSIC_NOTE_HALF, MUSIC_NOTE_OFF, MUSIC_NOTE_QUARTER, MUSIC_NOTE_SIXTEENTH, MUSIC_NOTE_WHOLE, NATURE, NATURE_PEOPLE, NAVIGATION, NEEDLE, NEST_PROTECT, 
          NEST_THERMOSTAT, NEWSPAPER, NFC, NFC_TAP, NFC_VARIANT, NUMERIC, NUMERIC_0_BOX, NUMERIC_0_BOX_MULTIPLE_OUTLINE, NUMERIC_0_BOX_OUTLINE, NUMERIC_1_BOX, 
          NUMERIC_1_BOX_MULTIPLE_OUTLINE, NUMERIC_1_BOX_OUTLINE, NUMERIC_2_BOX, NUMERIC_2_BOX_MULTIPLE_OUTLINE, NUMERIC_2_BOX_OUTLINE, NUMERIC_3_BOX, NUMERIC_3_BOX_MULTIPLE_OUTLINE, NUMERIC_3_BOX_OUTLINE, NUMERIC_4_BOX, NUMERIC_4_BOX_MULTIPLE_OUTLINE, 
          NUMERIC_4_BOX_OUTLINE, NUMERIC_5_BOX, NUMERIC_5_BOX_MULTIPLE_OUTLINE, NUMERIC_5_BOX_OUTLINE, NUMERIC_6_BOX, NUMERIC_6_BOX_MULTIPLE_OUTLINE, NUMERIC_6_BOX_OUTLINE, NUMERIC_7_BOX, NUMERIC_7_BOX_MULTIPLE_OUTLINE, NUMERIC_7_BOX_OUTLINE, 
          NUMERIC_8_BOX, NUMERIC_8_BOX_MULTIPLE_OUTLINE, NUMERIC_8_BOX_OUTLINE, NUMERIC_9_BOX, NUMERIC_9_BOX_MULTIPLE_OUTLINE, NUMERIC_9_BOX_OUTLINE, NUMERIC_9_PLUS_BOX, NUMERIC_9_PLUS_BOX_MULTIPLE_OUTLINE, NUMERIC_9_PLUS_BOX_OUTLINE, NUTRITON, 
          OFFICE, OIL, OMEGA, ONEDRIVE, OPEN_IN_APP, OPEN_IN_NEW, ORNAMENT, ORNAMENT_VARIANT, OUTBOX, PACKAGE, 
          PACKAGE_DOWN, PACKAGE_UP, PACKAGE_VARIANT, PACKAGE_VARIANT_CLOSED, PALETTE, PALETTE_ADVANCED, PANDA, PANDORA, PANORAMA, PANORAMA_FISHEYE, 
          PANORAMA_HORIZONTAL, PANORAMA_VERTICAL, PANORAMA_WIDE_ANGLE, PAPER_CUT_VERTICAL, PAPERCLIP, PARKING, PAUSE, PAUSE_CIRCLE, PAUSE_CIRCLE_OUTLINE, PAUSE_OCTAGON, 
          PAUSE_OCTAGON_OUTLINE, PEN, PENCIL, PENCIL_BOX, PENCIL_BOX_OUTLINE, PHARMACY, PHONE, PHONE_BLUETOOTH, PHONE_FORWARD, PHONE_HANGUP, 
          PHONE_IN_TALK, PHONE_LOCKED, PHONE_MISSED, PHONE_PAUSED, PHONE_SETTINGS, PIG, PILL, PIN, PIN_OFF, PINE_TREE, 
          PINE_TREE_BOX, PINTEREST, PINTEREST_BOX, PIZZA, PLAY, PLAY_BOX_OUTLINE, PLAY_CIRCLE, PLAY_CIRCLE_OUTLINE, PLAYLIST_MINUS, PLAYLIST_PLUS, 
          PLAYSTATION, PLUS, PLUS_BOX, PLUS_CIRCLE, PLUS_CIRCLE_OUTLINE, PLUS_NETWORK, PLUS_ONE, POCKET, POLL, POLL_BOX, 
          POLYMER, POPCORN, POUND, POUND_BOX, POWER, POWER_SETTINGS, PRESENTATION, PRESENTATION_PLAY, PRINTER, PRINTER_3D, 
          PULSE, PUZZLE, QRCODE, QUADCOPTER, QUALITY_HIGH, QUICKTIME, RADIATOR, RADIO, RADIO_TOWER, RADIOACTIVE, 
          RADIOBOX_BLANK, RADIOBOX_MARKED, RASPBERRYPI, RDIO, READ, READABILITY, RECEIPT, RECYCLE, REDO, REDO_VARIANT, 
          REFRESH, RELATIVE_SCALE, RELOAD, REMOTE, RENAME_BOX, REPEAT, REPEAT_OFF, REPEAT_ONCE, REPLAY, REPLY, 
          REPLY_ALL, REPRODUCTION, RESIZE_BOTTOM_RIGHT, RESPONSIVE, REWIND, RIBBON, ROCKET, ROTATE_3D, ROTATE_LEFT, ROTATE_LEFT_VARIANT, 
          ROTATE_RIGHT, ROTATE_RIGHT_VARIANT, ROUTES, RSS, RSS_BOX, RULER, RUN, SATELLITE, SATELLITE_VARIANT, SCALE, 
          SCALE_BATHROOM, SCHOOL, SCREEN_ROTATION, SCREEN_ROTATION_LOCK, SCRIPT, SD, SECURITY, SECURITY_NETWORK, SELECT, SELECT_ALL, 
          SELECT_INVERSE, SELECT_OFF, SEND, SERVER, SERVER_MINUS, SERVER_NETWORK, SERVER_NETWORK_OFF, SERVER_OFF, SERVER_PLUS, SERVER_REMOVE, 
          SERVER_SECURITY, SETTINGS, SETTINGS_BOX, SHAPE_PLUS, SHARE, SHARE_VARIANT, SHIELD, SHIELD_OUTLINE, SHOPPING, SHOPPING_MUSIC, 
          SHUFFLE, SIGMA, SIGN_CAUTION, SILVERWARE, SILVERWARE_FORK, SILVERWARE_SPOON, SILVERWARE_VARIANT, SIM_ALERT, SKIP_NEXT, SKIP_PREVIOUS, 
          SNAPCHAT, SNOWMAN, SORT, SORT_ALPHABETICAL, SORT_ASCENDING, SORT_DESCENDING, SORT_NUMERIC, SORT_VARIANT, SOUNDCLOUD, SOURCE_FORK, 
          SOURCE_PULL, SPEAKER, SPEAKER_OFF, SPEEDOMETER, SPELLCHECK, SPOTIFY, SPOTLIGHT, SPOTLIGHT_BEAM, STACKOVERFLOW, STAR, 
          STAR_CIRCLE, STAR_HALF, STAR_OUTLINE, STOCKING, STOP, STORE, STORE_24_HOUR, STOVE, SUBWAY, SWAP_HORIZONTAL, 
          SWAP_VERTICAL, SWIM, SWORD, SYNC, SYNC_ALERT, SYNC_OFF, TAB, TAB_UNSELECTED, TABLE, TABLE_COLUMN_PLUS_AFTER, 
          TABLE_COLUMN_PLUS_BEFORE, TABLE_COLUMN_REMOVE, TABLE_COLUMN_WIDTH, TABLE_EDIT, TABLE_LARGE, TABLE_ROW_HEIGHT, TABLE_ROW_PLUS_AFTER, TABLE_ROW_PLUS_BEFORE, TABLE_ROW_REMOVE, TABLET, 
          TABLET_ANDROID, TABLET_IPAD, TAG, TAG_FACES, TAG_MULTIPLE, TAG_OUTLINE, TAG_TEXT_OUTLINE, TAXI, TELEVISION, TELEVISION_GUIDE, 
          TEMPERATURE_CELSIUS, TEMPERATURE_FAHRENHEIT, TEMPERATURE_KELVIN, TENT, TERRAIN, TEXT_TO_SPEECH, TEXT_TO_SPEECH_OFF, TEXTURE, THEATER, THEME_LIGHT_DARK, 
          THERMOMETER, THERMOMETER_LINES, THUMB_DOWN, THUMB_DOWN_OUTLINE, THUMB_UP, THUMB_UP_OUTLINE, THUMBS_UP_DOWN, TICKET, TICKET_ACCOUNT, TIE, 
          TIMELAPSE, TIMER, TIMER_10, TIMER_3, TIMER_OFF, TIMER_SAND, TIMETABLE, TOGGLE_SWITCH, TOGGLE_SWITCH_OFF, TOOLTIP, 
          TOOLTIP_EDIT, TOOLTIP_IMAGE, TOOLTIP_OUTLINE, TOOLTIP_OUTLINE_PLUS, TOOLTIP_TEXT, TOR, TRAFFIC_LIGHT, TRAIN, TRAM, TRANSCRIBE, 
          TRANSCRIBE_CLOSE, TRANSFER, TREE, TRELLO, TRENDING_DOWN, TRENDING_NEUTRAL, TRENDING_UP, TROPHY, TROPHY_AWARD, TROPHY_VARIANT, 
          TRUCK, TSHIRT_CREW, TSHIRT_V, TUMBLR, TUMBLR_REBLOG, TWITCH, TWITTER, TWITTER_BOX, TWITTER_RETWEET, UBUNTU, 
          UNDO, UNDO_VARIANT, UNFOLD_LESS, UNFOLD_MORE, UNTAPPD, UPLOAD, USB, VECTOR_CURVE, VECTOR_POINT, VECTOR_SQUARE, 
          VERIFIED, VIBRATE, VIDEO, VIDEO_OFF, VIDEO_SWITCH, VIEW_AGENDA, VIEW_ARRAY, VIEW_CAROUSEL, VIEW_COLUMN, VIEW_DASHBOARD, 
          VIEW_DAY, VIEW_HEADLINE, VIEW_LIST, VIEW_MODULE, VIEW_QUILT, VIEW_STREAM, VIEW_WEEK, VIMEO, VK, VOICEMAIL, 
          VOLUME_HIGH, VOLUME_LOW, VOLUME_MEDIUM, VOLUME_OFF, WALK, WALLET, WALLET_GIFTCARD, WALLET_MEMBERSHIP, WALLET_TRAVEL, WATCH, 
          WATCH_EXPORT, WATCH_IMPORT, WATER, WATER_OFF, WATER_PUMP, WEATHER_CLOUDY, WEATHER_HAIL, WEATHER_LIGHTNING, WEATHER_NIGHT, WEATHER_PARTLYCLOUDY, 
          WEATHER_POURING, WEATHER_RAINY, WEATHER_SNOWY, WEATHER_SUNNY, WEATHER_SUNSET, WEATHER_SUNSET_DOWN, WEATHER_SUNSET_UP, WEATHER_WINDY, WEATHER_WINDY_VARIANT, WEB, 
          WEBCAM, WEIGHT, WEIGHT_KILOGRAM, WHATSAPP, WHEELCHAIR_ACCESSIBILITY, WHITE_BALANCE_AUTO, WHITE_BALANCE_INCANDESCENT, WHITE_BALANCE_IRRADESCENT, WHITE_BALANCE_SUNNY, WIFI, 
          WII, WIKIPEDIA, WINDOW_CLOSE, WINDOW_CLOSED, WINDOW_MAXIMIZE, WINDOW_MINIMIZE, WINDOW_OPEN, WINDOW_RESTORE, WINDOWS, WORDPRESS, 
          WORKER, WUNDERLIST, XBOX, XBOX_CONTROLLER, XBOX_CONTROLLER_OFF, XDA, XML, YEAST, YOUTUBE_PLAY, ZIP_BOX };
    }
  }
  
  private class MaterialDrawable extends Drawable {
    private int alpha = 255;
    
    private final Context context;
    
    private MaterialDrawableBuilder.IconValue icon;
    
    private final Rect mCachedRect = new Rect();
    
    private TextPaint paint;
    
    private int size = -1;
    
    public MaterialDrawable(Context param1Context, MaterialDrawableBuilder.IconValue param1IconValue, TextPaint param1TextPaint, int param1Int1, int param1Int2) {
      this.context = param1Context;
      this.icon = param1IconValue;
      this.paint = param1TextPaint;
      setSizePx(param1Int1);
      setAlpha(param1Int2);
      invalidateSelf();
    }
    
    public void clearColorFilter() {
      this.paint.setColorFilter(null);
    }
    
    public void draw(Canvas param1Canvas) {
      this.paint.setTextSize(getBounds().height());
      String str = MaterialIconUtils.getIconString(this.icon.ordinal());
      this.paint.getTextBounds(str, 0, 1, this.mCachedRect);
      float f1 = (getBounds().height() - this.mCachedRect.height()) / 2.0F;
      float f2 = this.mCachedRect.height();
      float f3 = this.mCachedRect.bottom;
      param1Canvas.drawText(str, getBounds().width() / 2.0F, f1 + f2 - f3, (Paint)this.paint);
    }
    
    public int getIntrinsicHeight() {
      return this.size;
    }
    
    public int getIntrinsicWidth() {
      return this.size;
    }
    
    public int getOpacity() {
      return this.alpha;
    }
    
    public boolean isStateful() {
      return true;
    }
    
    public void setAlpha(int param1Int) {
      this.alpha = param1Int;
      this.paint.setAlpha(param1Int);
    }
    
    public void setColorFilter(ColorFilter param1ColorFilter) {
      this.paint.setColorFilter(param1ColorFilter);
    }
    
    public MaterialDrawable setSizePx(int param1Int) {
      this.size = param1Int;
      setBounds(0, 0, param1Int, param1Int);
      invalidateSelf();
      return this;
    }
    
    public boolean setState(int[] param1ArrayOfint) {
      int i = this.paint.getAlpha();
      int j = this.alpha;
      this.paint.setAlpha(j);
      return (i != j);
    }
    
    public void setStyle(Paint.Style param1Style) {
      this.paint.setStyle(param1Style);
    }
  }
}


/* Location:              /opt/home/jayk-storage/Downloads/quadstellar/classes-dex2jar.jar!/net/steamcrafted/materialiconlib/MaterialDrawableBuilder.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */